const CONSONANTS=[
  {k:'ក',l:'Ka',ex:'ក្ដៅ = panas'},{k:'ខ',l:'Kha',ex:'ខ្ទឹម = bawang putih'},
  {k:'គ',l:'Ko',ex:'គោ = sapi'},{k:'ឃ',l:'Kho',ex:'ឃ្លាំ = mengintip'},
  {k:'ង',l:'Ngo',ex:'ងូតទឹក = mandi'},{k:'ច',l:'Cha',ex:'ចៃ = semut'},
  {k:'ឆ',l:'Chha',ex:'ឆ្ងុយ = lezat'},{k:'ជ',l:'Cho',ex:'ជោគជ័យ = sukses'},
  {k:'ឈ',l:'Chho',ex:'ឈ្នះ = menang'},{k:'ញ',l:'Nyo',ex:'ញ៉ាំ = makan'},
  {k:'ដ',l:'Da',ex:'ដើម = pohon'},{k:'ឋ',l:'Tha',ex:'ឋាន = tempat'},
  {k:'ឌ',l:'Do',ex:'ឌូ = seruling'},{k:'ឍ',l:'Dho',ex:'(jarang dipakai)'},
  {k:'ណ',l:'Na',ex:'ណែ = memberi saran'},{k:'ត',l:'Ta',ex:'ទួល = bukit'},
  {k:'ថ',l:'Tha',ex:'ថ្ងៃ = hari'},{k:'ទ',l:'To',ex:'ទឹក = air'},
  {k:'ធ',l:'Tho',ex:'ធ្លាក់ = jatuh'},{k:'ន',l:'No',ex:'នារី = wanita'},
  {k:'ប',l:'Ba',ex:'បាយ = nasi'},{k:'ផ',l:'Pha',ex:'ផ្ទះ = rumah'},
  {k:'ព',l:'Po',ex:'ពេល = waktu'},{k:'ភ',l:'Pho',ex:'ភ្លៀង = hujan'},
  {k:'ម',l:'Mo',ex:'ម្ហូប = makanan'},{k:'យ',l:'Yo',ex:'យប់ = malam'},
  {k:'រ',l:'Ro',ex:'រៀន = belajar'},{k:'ល',l:'Lo',ex:'លើ = di atas'},
  {k:'វ',l:'Vo',ex:'វ័យ = usia'},{k:'ស',l:'Sa',ex:'ស្នេហ៍ = cinta'},
  {k:'ហ',l:'Ha',ex:'ហូប = makan'},{k:'ឡ',l:'La',ex:'ឡើង = naik'},
  {k:'អ',l:'A',ex:'អរគុណ = terima kasih'}
];
const VOWELS=[
  {k:'អា',l:'aa',ex:'ចាន = piring'},{k:'អិ',l:'e / i',ex:'ទិញ = beli'},
  {k:'អី',l:'ii',ex:'ស្រី = perempuan'},{k:'អុ',l:'o',ex:'ចុះ = turun'},
  {k:'អូ',l:'uu',ex:'គោ = sapi'},{k:'អួ',l:'ua',ex:'ឃ្លួន = tubuh'},
  {k:'អើ',l:'ae',ex:'ស្ទើរ = hampir'},{k:'អឹ',l:'oe',ex:'ស្ទឹង = sungai'},
  {k:'អែ',l:'ae',ex:'ថ្ងែ = terang'},{k:'អៃ',l:'ai',ex:'ថ្ងៃ = hari'},
  {k:'អោ',l:'oo',ex:'ព្រោះ = karena'},{k:'អៅ',l:'au',ex:'ក្ដៅ = panas'},
  {k:'អំ',l:'om/am',ex:'ចំ = tepat'},{k:'អាំ',l:'am',ex:'ហ្នាំ = kebiasaan'},
  {k:'ឧ',l:'u',ex:'ឧ = vokal u'},{k:'ឩ',l:'uu',ex:'ឩ = vokal panjang'}
];
const DIGITS=[
  {k:'០',l:'0 — soun = nol'},{k:'១',l:'1 — muoy = satu'},
  {k:'២',l:'2 — pir = dua'},{k:'៣',l:'3 — bei = tiga'},
  {k:'៤',l:'4 — boun = empat'},{k:'៥',l:'5 — pram = lima'},
  {k:'៦',l:'6 — pram-muoy'},{k:'៧',l:'7 — pram-pir'},
  {k:'៨',l:'8 — pram-bei'},{k:'៩',l:'9 — pram-boun'}
];
const VOCAB={
  'Salam':[
    {k:'សួស្តី',r:'Suos-dei',m:'Halo',ex:'សួស្តី! — Halo, apa kabar?'},
    {k:'អរគុណ',r:'Ar-kun',m:'Terima kasih',ex:'អរគុណច្រើន! — Terima kasih banyak!'},
    {k:'សូមទោស',r:'Soum-toh',m:'Maaf / Permisi',ex:'សូមទោស — Permisi'},
    {k:'លាហើយ',r:'Lia-haey',m:'Selamat tinggal',ex:'លាហើយ! — Sampai jumpa!'},
    {k:'ចាស',r:'Chas',m:'Ya (wanita)',ex:'ចាស ខ្ញុំ — Ya, saya'},
    {k:'បាទ',r:'Bat',m:'Ya (pria)',ex:'បាទ ឋ — Ya, benar'},
    {k:'ទេ',r:'Te',m:'Tidak',ex:'ទេ អរគុណ — Tidak, terima kasih'},
    {k:'ខ្ញុំ',r:'Khnhom',m:'Saya / Aku',ex:'ខ្ញុំជាគ្រូ — Saya adalah guru'},
    {k:'អ្នក',r:'Neak',m:'Kamu / Anda',ex:'អ្នកមកពីណា? — Kamu dari mana?'},
    {k:'គាត់',r:'Koat',m:'Dia (hormat)',ex:'គាត់ជាគ្រូ — Dia adalah guru'},
    {k:'យើង',r:'Yeung',m:'Kita / Kami',ex:'យើងទៅ — Kita pergi'},
    {k:'ពួកគេ',r:'Puok-ke',m:'Mereka',ex:'ពួកគេហូប — Mereka makan'},
  ],
  'Keluarga':[
    {k:'ម្ដាយ',r:"M'day",m:'Ibu',ex:'ម្ដាយខ្ញុំ — Ibuku'},
    {k:'ឪពុក',r:'Ov-pok',m:'Ayah',ex:'ឪពុកខ្ញុំ — Ayahku'},
    {k:'បង',r:'Bong',m:'Kakak',ex:'បងស្រី — Kakak perempuan'},
    {k:'អូន',r:'Oun',m:'Adik',ex:'អូនប្រុស — Adik laki-laki'},
    {k:'កូន',r:'Koun',m:'Anak',ex:'កូនស្រី — Anak perempuan'},
    {k:'ប្ដី',r:"B'dei",m:'Suami',ex:'ប្ដីខ្ញុំ — Suami saya'},
    {k:'ប្រពន្ធ',r:'Bra-pon',m:'Istri',ex:'ប្រពន្ធខ្ញុំ — Istri saya'},
    {k:'ជីដូន',r:'Chi-don',m:'Nenek',ex:'ជីដូនចាស់ — Nenek tua'},
    {k:'ជីតា',r:'Chi-ta',m:'Kakek',ex:'ជីតាខ្ញុំ — Kakekku'},
    {k:'ប្អូន',r:"B'aon",m:'Saudara',ex:'ប្អូនខ្ញុំ — Saudara saya'},
    {k:'ភរិយា',r:'Phari-ya',m:'Istri (formal)',ex:'ភរិយារបស់គាត់ — Istrinya'},
    {k:'ស្វាមី',r:'Svami',m:'Suami (formal)',ex:'ស្វាមីរបស់នាង — Suaminya'},
  ],
  'Makanan':[
    {k:'បាយ',r:'Bay',m:'Nasi',ex:'ញ៉ាំបាយ — Makan nasi'},
    {k:'ម្ហូប',r:'Mhoup',m:'Lauk / Makanan',ex:'ម្ហូបឆ្ងុញ — Makanan enak'},
    {k:'ទឹក',r:'Tik',m:'Air',ex:'ទឹកត្រជាក់ — Air dingin'},
    {k:'ត្រី',r:'Trei',m:'Ikan',ex:'ត្រីអំបិល — Ikan asin'},
    {k:'សាច់',r:'Sach',m:'Daging',ex:'សាច់មាន់ — Daging ayam'},
    {k:'បន្លែ',r:'Bonlae',m:'Sayuran',ex:'បន្លែស្រស់ — Sayuran segar'},
    {k:'ផ្លែឈើ',r:"Plae ch'eu",m:'Buah-buahan',ex:'ផ្លែឈើផ្អែម — Buah manis'},
    {k:'ស្ករ',r:"S'kor",m:'Gula',ex:'ស្ករក្រហម — Gula merah'},
    {k:'អំបិល',r:'Ambel',m:'Garam',ex:'អំបិល — Garam'},
    {k:'ណាំបញ្ចុក',r:'Nam-ban-chok',m:'Mie Khmer',ex:'ណាំបញ្ចុក — Mie khas Khmer'},
    {k:'អាម៉ុក',r:'A-mok',m:'Amok (masakan)',ex:'អាម៉ុកត្រី — Amok ikan'},
    {k:'បបរ',r:'Bor-bor',m:'Bubur',ex:'បបរ — Bubur nasi Khmer'},
  ],
  'Tempat':[
    {k:'ផ្ទះ',r:'Pteah',m:'Rumah',ex:'ផ្ទះធំ — Rumah besar'},
    {k:'ទីក្រុង',r:'Ti-krong',m:'Kota',ex:'ទីក្រុងភ្នំពេញ — Kota Phnom Penh'},
    {k:'ស្ទឹង',r:"S'tong",m:'Sungai',ex:'ស្ទឹងមេគង្គ — Sungai Mekong'},
    {k:'ភ្នំ',r:'Phnom',m:'Gunung',ex:'ភ្នំ — Gunung'},
    {k:'វត្ត',r:'Vot',m:'Kuil / Pura',ex:'វត្តអង្គរ — Angkor Wat'},
    {k:'ទីផ្សារ',r:'Ti-psar',m:'Pasar',ex:'ទីផ្សារថ្មី — Pasar Baru'},
    {k:'ផ្លូវ',r:'Phlov',m:'Jalan',ex:'ផ្លូវវែង — Jalan panjang'},
    {k:'សមុទ្រ',r:'Sa-mot',m:'Laut',ex:'ឆ្នេរ = pantai'},
    {k:'ព្រៃ',r:'Prey',m:'Hutan',ex:'ព្រៃខ្ទម — Hutan lebat'},
    {k:'ប្រទេស',r:"B'ro-tes",m:'Negara',ex:'ប្រទេសខ្មែរ — Negara Kamboja'},
    {k:'ខេត្ត',r:'Khet',m:'Provinsi',ex:'ខេត្តសៀមរាប — Siem Reap'},
    {k:'ភូមិ',r:'Phumi',m:'Desa',ex:'ភូមិតូច — Desa kecil'},
  ],
  'Alam':[
    {k:'ព្រះអាទិត្យ',r:'Preah-atit',m:'Matahari',ex:'ព្រះអាទិត្យរះ — Matahari terbit'},
    {k:'ព្រះចន្ទ',r:'Preah-chan',m:'Bulan',ex:'ព្រះចន្ទពេញ — Bulan purnama'},
    {k:'ផ្ការ',r:'Phkar',m:'Bunga',ex:'ផ្ការឆ្ងោត — Bunga harum'},
    {k:'ភ្លៀង',r:'Phliang',m:'Hujan',ex:'ភ្លៀងធ្លាក់ — Hujan turun'},
    {k:'ខ្យល់',r:'Khyal',m:'Angin',ex:'ខ្យល់ត្រជាក់ — Angin sejuk'},
    {k:'ដី',r:'Dei',m:'Tanah',ex:'ដីក្រហម — Tanah merah'},
    {k:'ថ្ម',r:'Thma',m:'Batu',ex:'ថ្មធំ — Batu besar'},
    {k:'ភ្លើង',r:'Phloeung',m:'Api',ex:'ភ្លើង — Api'},
    {k:'ទំនប់',r:'Tom-nob',m:'Bendungan',ex:'ទំនប់ទឹក — Bendungan air'},
    {k:'ឧទ្យាន',r:'Ot-yearn',m:'Taman',ex:'ឧទ្យានជាតិ — Taman Nasional'},
    {k:'ក្ដៅ',r:"K'dao",m:'Panas',ex:'ថ្ងៃក្ដៅ — Hari panas'},
    {k:'ត្រជាក់',r:'Tra-chak',m:'Dingin',ex:'ត្រជាក់ — Dingin sekali'},
  ],
  'Warna':[
    {k:'ក្រហម',r:'Kra-hom',m:'Merah',ex:'ផ្ការក្រហម — Bunga merah'},
    {k:'ខៀវ',r:'Khiev',m:'Biru',ex:'មេឃខៀវ — Langit biru'},
    {k:'លឿង',r:'Loeung',m:'Kuning',ex:'ព្រះអាទិត្យលឿង'},
    {k:'ស',r:'Sor',m:'Putih',ex:'ពណ៌ស — Putih bersih'},
    {k:'ខ្មៅ',r:'Khmau',m:'Hitam',ex:'ពពកខ្មៅ — Awan hitam'},
    {k:'បៃតង',r:'Bai-tong',m:'Hijau',ex:'ស្មៅបៃតង — Rumput hijau'},
    {k:'ស្វាយ',r:'Svay',m:'Ungu',ex:'ពណ៌ស្វាយ — Warna ungu'},
    {k:'ត្នោត',r:"T'not",m:'Oranye',ex:'ពណ៌ត្នោត — Warna oranye'},
    {k:'ប្រផ្លោ',r:"B'ra-phlo",m:'Coklat',ex:'ដីប្រផ្លោ — Tanah coklat'},
    {k:'ប្រផ្អូស',r:"B'ra-phaus",m:'Abu-abu',ex:'ថ្មប្រផ្អូស'},
    {k:'ទំពំ',r:'Tom-pom',m:'Pink',ex:'ផ្ការទំពំ — Bunga pink'},
    {k:'ប្រ​ Home',r:'Bra-hom',m:'Merah muda',ex:'ពណ៌ — Warna'},
  ],
  'Waktu':[
    {k:'ថ្ងៃ',r:'Thngai',m:'Hari / Siang',ex:'ថ្ងៃនេះ — Hari ini'},
    {k:'យប់',r:'Yup',m:'Malam',ex:'យប់មិញ — Tadi malam'},
    {k:'ព្រឹក',r:'Preuk',m:'Pagi',ex:'ព្រឹកស្រស់ — Pagi cerah'},
    {k:'ល្ងាច',r:'Lngeach',m:'Sore',ex:'ល្ងាចល្អ — Sore indah'},
    {k:'ថ្ងៃត្រង់',r:"Thngai t'rong",m:'Tengah hari',ex:'ថ្ងៃត្រង់ — Siang hari'},
    {k:'ស្អែក',r:"S'aek",m:'Besok',ex:'ស្អែកផ្ដើម — Mulai besok'},
    {k:'ម្សិល',r:"M'sel",m:'Kemarin',ex:'ម្សិលមិញ — Tadi kemarin'},
    {k:'ឥឡូវ',r:'Ei-lov',m:'Sekarang',ex:'ឥឡូវនេះ — Sekarang ini'},
    {k:'ម៉ោង',r:'Maong',m:'Jam',ex:'ម៉ោងប៉ុន្មាន? — Jam berapa?'},
    {k:'នាទី',r:'Nea-ti',m:'Menit',ex:'ម្ភៃនាទី — Dua puluh menit'},
    {k:'ខែ',r:'Khae',m:'Bulan',ex:'ខែ​មករា — Bulan Januari'},
    {k:'ឆ្នាំ',r:'Chhnham',m:'Tahun',ex:'ឆ្នាំ​នេះ — Tahun ini'},
  ],
  'Tubuh':[
    {k:'ក្បាល',r:"K'bal",m:'Kepala',ex:'ក្បាលហ្$(ឈ) — Kepala sakit'},
    {k:'ភ្នែក',r:'Phnek',m:'Mata',ex:'ភ្នែកស្អាត — Mata cantik'},
    {k:'ច្រមុះ',r:"Ch'romuh",m:'Hidung',ex:'ច្រមុះ — Hidung'},
    {k:'ត្រចៀក',r:'Tra-chiek',m:'Telinga',ex:'ត្រចៀក — Telinga'},
    {k:'មាត់',r:'Moat',m:'Mulut',ex:'មាត់ — Mulut'},
    {k:'ធ្មេញ',r:'Thmein',m:'Gigi',ex:'ធ្មេញស — Gigi putih'},
    {k:'ដៃ',r:'Dai',m:'Tangan',ex:'ដៃស្ដាំ — Tangan kanan'},
    {k:'ជើង',r:'Cheung',m:'Kaki',ex:'ជើងខ្លី — Kaki pendek'},
    {k:'ពោះ',r:'Puoh',m:'Perut',ex:'ពោះ — Perut'},
    {k:'ចិត្ត',r:'Chet',m:'Hati',ex:'ចិត្តល្អ — Hati baik'},
    {k:'ខ្លួន',r:'Khloun',m:'Tubuh / Diri',ex:'ខ្លួនខ្ញុំ — Tubuh saya'},
    {k:'ក',r:'Ko',m:'Leher',ex:'ក — Leher'},
  ],
  'Emosi':[
    {k:'រីករាយ',r:'Rik-reay',m:'Bahagia',ex:'ខ្ញុំរីករាយ — Saya bahagia'},
    {k:'ស្រឡាញ់',r:"S'ranh",m:'Mencintai',ex:'ខ្ញុំស្រឡាញ់ — Saya mencintai'},
    {k:'ខឹង',r:'Kheng',m:'Marah',ex:'គាត់ខឹង — Dia marah'},
    {k:'ខ្លាច',r:'Khlaach',m:'Takut',ex:'ខ្ញុំខ្លាច — Saya takut'},
    {k:'ព្រួយ',r:'Pruoy',m:'Khawatir',ex:'ខ្ញុំព្រួយ — Saya khawatir'},
    {k:'ស្នេហ៍',r:'Sne',m:'Cinta (noun)',ex:'ស្នេហ៍ពិត — Cinta sejati'},
    {k:'ចង់',r:'Chong',m:'Mau / Ingin',ex:'ខ្ញុំចង់ — Saya ingin'},
    {k:'ស្ងប់',r:"S'ngob",m:'Tenang',ex:'ចិត្តស្ងប់ — Hati tenang'},
    {k:'ឈឺ',r:'Chheuu',m:'Sakit',ex:'ខ្ញុំឈឺ — Saya sakit'},
    {k:'នឿយ',r:'Noeuy',m:'Lelah',ex:'ខ្ញុំនឿយ — Saya lelah'},
    {k:'ស្ទូច',r:"S'touch",m:'Sedih',ex:'ខ្ញុំស្ទូច — Saya sedih'},
    {k:'សប្បាយ',r:'Sabay',m:'Senang / Enak',ex:'ខ្ញុំសប្បាយ — Saya senang'},
  ],
};
const PHRASES=[
  {cat:'Sapaan',title:'Salam & Perkenalan',rows:[
    {k:'សួស្តី!',r:'Suos-dei!',i:'Halo!',n:'Salam paling umum'},
    {k:'ជំរាបសួរ',r:'Chumreap-suor',i:'Selamat (formal)',n:'Digunakan dalam situasi resmi'},
    {k:'អ្នកសុខសប្បាយទេ?',r:'Neak sok sabay te?',i:'Apa kabar?',n:'Pertanyaan umum sehari-hari'},
    {k:'ខ្ញុំសុខសប្បាយ',r:'Khnhom sok sabay',i:'Saya baik-baik saja',n:'Jawaban standar'},
    {k:'ឈ្មោះអ្នកគឺអ្វី?',r:'Chhmua neak keu avei?',i:'Siapa nama kamu?',n:'Cara bertanya nama'},
    {k:'ឈ្មោះខ្ញុំ...',r:'Chhmua khnhom...',i:'Nama saya adalah...',n:'Perkenalan diri'},
    {k:'ខ្ញុំមកពីឥណ្ឌូនេស៊ី',r:'Khnhom mok pi Indonesia',i:'Saya dari Indonesia',n:'Menyebut asal negara'},
    {k:'អ្នកមកពីណា?',r:'Neak mok pi na?',i:'Kamu dari mana?',n:'Bertanya asal'},
    {k:'ខ្ញុំរីករាយដែលបានជួប',r:'Khnhom rik-reay del ban chuop',i:'Senang berkenalan denganmu',n:'Ucapan perkenalan'},
    {k:'អ្នកអាយុប៉ុន្មាន?',r:'Neak ayu ponman?',i:'Berapa umurmu?',n:'Bertanya umur'},
  ]},
  {cat:'Kesopanan',title:'Ucapan Sopan & Terima Kasih',rows:[
    {k:'អរគុណ',r:'Ar-kun',i:'Terima kasih',n:'Paling umum'},
    {k:'អរគុណច្រើន',r:'Ar-kun chraen',i:'Terima kasih banyak',n:'Lebih ekspresif'},
    {k:'អរគុណណាស់',r:'Ar-kun nas',i:'Terima kasih sekali',n:'Penekanan rasa syukur'},
    {k:'សូមទោស',r:'Soum toh',i:'Maaf / Permisi',n:'Meminta maaf ringan'},
    {k:'ខ្ញុំសោកស្ដាយ',r:"Khnhom saok s'dai",i:'Saya minta maaf (tulus)',n:'Permintaan maaf serius'},
    {k:'អត់ទោស',r:'At toh',i:'Tidak apa-apa',n:'Jawaban atas permintaan maaf'},
    {k:'រីករាយ',r:'Rik-reay',i:'Sama-sama',n:'Balasan terima kasih'},
    {k:'សូម',r:'Soum',i:'Tolong / Silakan',n:'Kata sopan serbaguna'},
    {k:'ជំរាបលា',r:'Chumreap lia',i:'Selamat tinggal (formal)',n:'Perpisahan formal'},
    {k:'ជួបគ្នាស្អែក',r:"Chuop knia s'aek",i:'Sampai jumpa besok',n:'Perpisahan informal'},
  ]},
  {cat:'Bertanya',title:'Pertanyaan & Meminta Bantuan',rows:[
    {k:'ខ្ញុំមិនយល់',r:'Khnhom min yul',i:'Saya tidak mengerti',n:''},
    {k:'សូមថាម្ដងទៀត',r:"Soum tha m'dong tiet",i:'Tolong ulangi lagi',n:''},
    {k:'ថាបន្ទន់',r:'Tha bon-ton',i:'Tolong berbicara pelan-pelan',n:''},
    {k:'ប៉ុន្មានលុយ?',r:'Ponman luy?',i:'Berapa harganya?',n:''},
    {k:'នៅឯណា?',r:'Now ae na?',i:'Di mana?',n:''},
    {k:'ម៉ោងប៉ុន្មាន?',r:'Maong ponman?',i:'Jam berapa?',n:''},
    {k:'ហេតុអ្វី?',r:'Het avei?',i:'Kenapa?',n:''},
    {k:'ធ្វើម៉ោះ?',r:'Tveu mach?',i:'Bagaimana?',n:''},
    {k:'អ្នកជួយខ្ញុំបានទេ?',r:'Neak chuoy khnhom ban te?',i:'Bisakah kamu bantu saya?',n:''},
    {k:'អ្នកនិយាយខ្មែរបានទេ?',r:'Neak niyay Khmer ban te?',i:'Kamu bisa bahasa Khmer?',n:''},
  ]},
  {cat:'Restoran',title:'Di Restoran, Warung & Pasar',rows:[
    {k:'ខ្ញុំចង់ញ៉ាំ',r:'Khnhom jong nyam',i:'Saya ingin makan',n:''},
    {k:'ម្ហូបអ្វីឆ្ងុញ?',r:'Mhoup avei chhnhunh?',i:'Makanan apa yang enak?',n:''},
    {k:'ឆ្ងុញណាស់!',r:'Chhnhunh nas!',i:'Sangat enak!',n:''},
    {k:'ទឹកមួយកែវ',r:'Tik muoy kaev',i:'Segelas air',n:''},
    {k:'ម្ហូបរំហោត',r:'Mhoup romhot',i:'Makanan pedas',n:''},
    {k:'ចំណងជើង',r:'Cham-nong cheung',i:'Menu',n:''},
    {k:'គ្រប់គ្រាន់',r:'Kroup-kroan',i:'Cukup / Kenyang',n:''},
    {k:'គិតថ្លៃ',r:'Kit thlai',i:'Bayar / Hitung harga',n:''},
    {k:'ថ្លៃណាស់',r:'Thlai nas',i:'Sangat mahal',n:''},
    {k:'ថោកណាស់',r:'Thoak nas',i:'Sangat murah',n:''},
  ]},
  {cat:'Perjalanan',title:'Perjalanan & Transportasi',rows:[
    {k:'ទៅណា?',r:'Tov na?',i:'Mau ke mana?',n:''},
    {k:'ខ្ញុំចង់ទៅ...',r:'Khnhom jong tov...',i:'Saya ingin pergi ke...',n:''},
    {k:'ឆ្ងាយទេ?',r:'Chngay te?',i:'Jauh tidak?',n:''},
    {k:'ជិះ / ដើរ',r:'Chih / Daer',i:'Naik kendaraan / Jalan kaki',n:''},
    {k:'ឈប់',r:'Chhob',i:'Berhenti',n:''},
    {k:'ត្រង់',r:'Trong',i:'Lurus',n:''},
    {k:'ងាកស្ដាំ',r:"Neak s'dam",i:'Belok kanan',n:''},
    {k:'ងាកឆ្វេង',r:'Neak chhveng',i:'Belok kiri',n:''},
    {k:'ជំលីនាំខ្ញុំ',r:'Chom-li noam khnhom',i:'Tolong antar saya',n:''},
    {k:'ស្ថានីយ',r:'Sthaniy',i:'Stasiun / Terminal',n:''},
  ]},
  {cat:'Kesehatan',title:'Kesehatan & Darurat',rows:[
    {k:'ខ្ញុំឈឺ',r:'Khnhom chheuu',i:'Saya sakit',n:''},
    {k:'ខ្ញុំត្រូវការវេជ្ជបណ្ឌិត',r:'Khnhom trov kar veach-bun-dit',i:'Saya butuh dokter',n:''},
    {k:'ឈឺក្បាល',r:"Chheuu k'bal",i:'Sakit kepala',n:''},
    {k:'ឈឺពោះ',r:'Chheuu puoh',i:'Sakit perut',n:''},
    {k:'ជួយខ្ញុំផង!',r:'Chuoy khnhom phong!',i:'Tolong bantu saya!',n:'Darurat'},
    {k:'ហៅប៉ូលីស!',r:'Hao Polis!',i:'Panggil polisi!',n:''},
    {k:'ថ្នាំ',r:'Thnhom',i:'Obat',n:''},
    {k:'ពេទ្យ',r:'Peit',i:'Dokter / Rumah sakit',n:''},
    {k:'គ្រោះថ្នាក់',r:'Kruos-thnak',i:'Bahaya / Kecelakaan',n:''},
    {k:'ជំងឺ',r:'Chumngeu',i:'Penyakit',n:''},
  ]},
];
const NUMBERS=[
  {n:'0',k:'សូន្យ',r:'Soun',m:'Nol'},
  {n:'1',k:'មួយ',r:'Muoy',m:'Satu'},
  {n:'2',k:'ពីរ',r:'Pir',m:'Dua'},
  {n:'3',k:'បី',r:'Bei',m:'Tiga'},
  {n:'4',k:'បួន',r:'Boun',m:'Empat'},
  {n:'5',k:'ប្រាំ',r:'Pram',m:'Lima'},
  {n:'6',k:'ប្រាំមួយ',r:'Pram-muoy',m:'Enam'},
  {n:'7',k:'ប្រាំពីរ',r:'Pram-pir',m:'Tujuh'},
  {n:'8',k:'ប្រាំបី',r:'Pram-bei',m:'Delapan'},
  {n:'9',k:'ប្រាំបួន',r:'Pram-boun',m:'Sembilan'},
  {n:'10',k:'ដប់',r:'Dop',m:'Sepuluh'},
  {n:'11',k:'ដប់មួយ',r:'Dop-muoy',m:'Sebelas'},
  {n:'12',k:'ដប់ពីរ',r:'Dop-pir',m:'Dua belas'},
  {n:'13',k:'ដប់បី',r:'Dop-bei',m:'Tiga belas'},
  {n:'15',k:'ដប់ប្រាំ',r:'Dop-pram',m:'Lima belas'},
  {n:'20',k:'ម្ភៃ',r:'Mpei',m:'Dua puluh'},
  {n:'21',k:'ម្ភៃមួយ',r:'Mpei-muoy',m:'Dua puluh satu'},
  {n:'30',k:'សាមសិប',r:'Sam-sib',m:'Tiga puluh'},
  {n:'40',k:'សែសិប',r:'Se-sib',m:'Empat puluh'},
  {n:'50',k:'ហាសិប',r:'Ha-sib',m:'Lima puluh'},
  {n:'60',k:'ហុកសិប',r:'Hok-sib',m:'Enam puluh'},
  {n:'70',k:'ចិតសិប',r:'Chet-sib',m:'Tujuh puluh'},
  {n:'80',k:'ប៉ែតសិប',r:'Paet-sib',m:'Delapan puluh'},
  {n:'90',k:'កៅសិប',r:'Kau-sib',m:'Sembilan puluh'},
  {n:'100',k:'មួយរយ',r:'Muoy-roi',m:'Seratus'},
  {n:'500',k:'ប្រាំរយ',r:'Pram-roi',m:'Lima ratus'},
  {n:'1.000',k:'មួយពាន់',r:'Muoy-poan',m:'Seribu'},
  {n:'5.000',k:'ប្រាំពាន់',r:'Pram-poan',m:'Lima ribu'},
  {n:'10.000',k:'មួយម៉ឺន',r:'Muoy-meun',m:'Sepuluh ribu'},
  {n:'100.000',k:'មួយសែន',r:'Muoy-saen',m:'Seratus ribu'},
  {n:'1.000.000',k:'មួយលាន',r:'Muoy-lean',m:'Satu juta'},
];
const GRAMMAR=[
  {ico:'🔤',title:'Struktur Kalimat (SPO)',body:'Bahasa Khmer menggunakan pola <strong>Subjek – Predikat – Objek</strong>, mirip Indonesia. Tidak ada konjugasi kata kerja — waktu ditandai kata keterangan waktu.',k:'ខ្ញុំញ៉ាំបាយ',r:'Khnhom nyam bay',i:'Saya makan nasi'},
  {ico:'⏰',title:'Kata Kerja & Aspek Waktu',body:'Kata kerja tidak berubah bentuk. <strong>បាន (ban)</strong> = sudah, <strong>នឹង (neng)</strong> = akan, <strong>កំពុង (kompung)</strong> = sedang.',k:'ខ្ញុំកំពុងរៀន',r:'Khnhom kompung rien',i:'Saya sedang belajar'},
  {ico:'🤝',title:'Kata Ganti Orang',body:'Sangat memperhatikan tingkat kesopanan. <strong>ខ្ញុំ</strong> = Saya, <strong>អ្នក</strong> = Kamu, <strong>លោក</strong> = Bapak (hormat), <strong>នាង</strong> = Dia wanita.',k:'លោកជានរណា?',r:'Lok chea norona?',i:'Bapak adalah siapa?'},
  {ico:'❓',title:'Kalimat Tanya',body:'Tambah <strong>ទេ (te)</strong> di akhir untuk pertanyaan ya/tidak. Kata tanya: <strong>ហេតុអ្វី</strong> = kenapa, <strong>ណា</strong> = mana, <strong>ប៉ុន្មាន</strong> = berapa.',k:'អ្នកហូបបានទេ?',r:'Neak houp ban te?',i:'Kamu bisa makan tidak?'},
  {ico:'🚫',title:'Kalimat Negatif',body:'Gunakan <strong>មិន...ទេ (min...te)</strong>. Kata <strong>មិន</strong> diletakkan sebelum kata kerja, <strong>ទេ</strong> di akhir kalimat.',k:'ខ្ញុំមិនទៅទេ',r:'Khnhom min tov te',i:'Saya tidak pergi'},
  {ico:'📏',title:'Kata Klasifikator',body:'Bahasa Khmer pakai kata klasifikator. <strong>នាក់ (neak)</strong> untuk orang, <strong>ក្បាល</strong> untuk hewan, <strong>ដើម</strong> untuk pohon.',k:'មនុស្សម្នាក់',r:"Mnus m'neak",i:'Satu orang (human + klasifikator)'},
  {ico:'🎭',title:'Tingkat Kesopanan',body:'Ada sistem tingkatan bahasa: bahasa rakyat (ភាសាប្រជ) dan bahasa istana (ភាសារាជការ). Kata-kata berbeda untuk orang biasa vs raja dan biksu.',k:'ព្រះអង្គស្វាយ',r:'Preah-ong svay',i:'Baginda makan (bahasa raja)'},
  {ico:'➕',title:'Kata Sifat & Posisi',body:'Kata sifat diletakkan <strong>setelah</strong> kata benda. <strong>ផ្ទះធំ</strong> (rumah besar), <strong>ក្មេងស្អាត</strong> (anak cantik).',k:'ផ្ទះធំ',r:'Pteah thom',i:'Rumah besar (rumah + besar)'},
  {ico:'🔗',title:'Kata Penghubung',body:'<strong>និង (ning)</strong> = dan, <strong>ឬ (reu)</strong> = atau, <strong>ប៉ុន្ដែ (bontae)</strong> = tapi, <strong>ព្រោះ (pruoh)</strong> = karena.',k:'ខ្ញុំនិងអ្នក',r:'Khnhom ning neak',i:'Saya dan kamu'},
];
const SONGS=[
  {emoji:'🌸',title:'ស្រីគ្រឹស្ថ',titleIndo:'Srey Kres — Gadis Kristal',singer:'Ros Sereysothea (1960an)',desc:'Lagu cinta klasik era emas musik Khmer, salah satu yang paling dicintai sepanjang masa.',
  lyrics:[
    {k:'ស្រីគ្រឹស្ថ ស្អាតពណ៌ស',r:"Srey kres s'at poa sor",i:'Gadis kristal cantik berkulit putih',n:'ស្រី = gadis'},
    {k:'ភ្នែកស្រស់ ដូចផ្ការ',r:'Phnek sros douch phkar',i:'Mata indah seperti bunga',n:'ភ្នែក = mata'},
    {k:'ចិត្តខ្ញុំ ស្រឡាញ់នាង',r:"Chet khnhom s'ranh neang",i:'Hatiku mencintainya',n:'ចិត្ត = hati'},
    {k:'ស្នើសុំ ចងស្រស់',r:"S'noe-som chong sros",i:'Memohon untuk bersatu',n:'ស្នើ = memohon'},
    {k:'ខ្ញុំស្រឡាញ់អ្នក',r:"Khnhom s'ranh neak",i:'Aku mencintaimu',n:'ស្រឡាញ់ = cinta'},
    {k:'ជារចិត្តពិត',r:'Chea ro chet pit',i:'Dengan hati yang tulus',n:'ពិត = tulus/nyata'},
    {k:'ពុំចង់ឃ្លាតចាក',r:'Pom chong khloat chak',i:'Tidak mau berpisah',n:'ឃ្លាត = berpisah'},
    {k:'គ្នារហូតដល់ស្លាប់',r:'Knia rohout dal slap',i:'Bersama hingga akhir hayat',n:'ស្លាប់ = mati'},
  ]},
  {emoji:'🌙',title:'ព្រះចន្ទ',titleIndo:'Preah Chan — Oh Bulan',singer:'Sinn Sisamouth (Legenda)',desc:'Lagu romantis paling ikonik dari raja musik Kamboja yang tiada tara.',
  lyrics:[
    {k:'ព្រះចន្ទ ពេញ រះ',r:'Preah chan penh reah',i:'Bulan purnama bersinar',n:'ព្រះចន្ទ = bulan'},
    {k:'លើ ទឹក ប្រណ្ដៅ',r:'Leu tik bron-dau',i:'Di atas air yang tenang',n:'ទឹក = air'},
    {k:'ខ្ញុំ នឹក ដល់ ម្ង',r:'Khnhom nek dal mong',i:'Aku teringat kenangan',n:'នឹក = teringat'},
    {k:'នៃ ព្រឹក មួយ',r:'Nai preuk muoy',i:'Dari suatu pagi hari',n:'ព្រឹក = pagi'},
    {k:'ផ្ការ ឈ្លក់',r:'Phkar chhlok',i:'Bunga mekar',n:'ផ្ការ = bunga'},
    {k:'ត្រជាក់ ព្រឹក',r:'Tra-chak preuk',i:'Sejuk di pagi hari',n:'ត្រជាក់ = sejuk'},
    {k:'ស្នេហ៍ ពិត ពុំ ស្លាប់',r:'Sne pit pom slap',i:'Cinta sejati tidak mati',n:'ស្នេហ៍ = cinta'},
    {k:'ជានិច្ចកាល',r:'Chea noch kal',i:'Untuk selamanya',n:'និច្ច = selamanya'},
  ]},
  {emoji:'🏯',title:'វត្តអង្គរ',titleIndo:'Vot Angkor — Angkor Wat',singer:'Lagu Kebanggaan Nasional',desc:'Lagu keagungan tentang Angkor Wat, simbol kejayaan peradaban Khmer.',
  lyrics:[
    {k:'អង្គរវត្ត ល្បីល្បាញ',r:'Angkor Vat lbei lbanh',i:'Angkor Wat yang termasyhur',n:'ល្បី = terkenal'},
    {k:'បេតិកភណ្ឌ ខ្មែររបស់',r:'Betik-phon Khmer robos',i:'Warisan milik bangsa Khmer',n:'បេតិកភណ្ឌ = warisan'},
    {k:'ស្ថានភព ដែល យើងស្រឡាញ់',r:"Sthan-phop del yeung s'ranh",i:'Warisan yang kita cintai',n:'ស្រឡាញ់ = cintai'},
    {k:'ភ្នំពេញ ស្ថិតជា ខ្ទប',r:'Phnom Penh sthet chea khtob',i:'Phnom Penh berdiri kokoh',n:'ស្ថិត = berdiri'},
    {k:'ប្រជាខ្មែរ ជាទី ស្រឡាញ់',r:"Prochea Khmer chea ti s'ranh",i:'Rakyat Khmer yang tercinta',n:'ប្រជា = rakyat'},
    {k:'រីករំចម្រើន ជានិច្ច',r:'Rik-rom chamroeun chea noch',i:'Berkembang maju selamanya',n:'ចម្រើន = berkembang'},
    {k:'ខ្មែររស់ ជានិច្ចនិរន្ដ',r:'Khmer ros chea noch nirant',i:'Khmer hidup abadi',n:'រស់ = hidup'},
    {k:'ជាតិ ខ្មែរ រុងរឿង',r:'Cheat Khmer rong-roeung',i:'Bangsa Khmer berjaya',n:'ជាតិ = bangsa'},
  ]},
  {emoji:'🌺',title:'ដំណើរស្នេហ៍',titleIndo:'Damnear Sne — Perjalanan Cinta',singer:'Lagu Pop Khmer Modern',desc:'Balada romantis tentang perjalanan dua insan yang saling mencintai.',
  lyrics:[
    {k:'ដំណើរស្នេហ៍ ដែលយើងហើរ',r:'Damnear sne del yeung haer',i:'Perjalanan cinta yang kita lalui',n:'ដំណើរ = perjalanan'},
    {k:'ពីព្រឹក ដល់យប់',r:'Pi preuk dal yup',i:'Dari pagi hingga malam',n:'ព្រឹក = pagi, យប់ = malam'},
    {k:'ជាមួយ គ្នា ជានិច្ច',r:'Chea muoy knia chea noch',i:'Bersama selamanya',n:'ជាមួយ = bersama'},
    {k:'ស្នេហ៍ ពិត ពុំ ស្លាប់',r:'Sne pit pom slap',i:'Cinta sejati tidak mati',n:'ពិត = sejati'},
    {k:'ចាប់ ដៃ ដើរ ជាមួយ',r:'Chap dai daer chea muoy',i:'Bergandengan tangan bersama',n:'ចាប់ = pegang'},
    {k:'ទៅ ចុង ផ្លូវ ស្នេហ៍',r:"Tov chong phlov sne",i:'Menuju ujung jalan cinta',n:'ចុង = ujung'},
    {k:'ស្នេហ៍ ស្ងប់ ស្ងាត់',r:"Sne s'ngob s'ngat",i:'Cinta yang tenang dan damai',n:'ស្ងប់ = tenang'},
    {k:'ដូច ភ្នំ ជ្រោះ',r:'Douch phnom chroh',i:'Seperti lembah pegunungan',n:'ភ្នំ = gunung'},
  ]},
  {emoji:'🌾',title:'ស្រែ',titleIndo:'Srae — Sawah',singer:'Lagu Tradisional Petani',desc:'Lagu tradisional tentang kehidupan petani Khmer yang akrab dengan sawah.',
  lyrics:[
    {k:'ស្រែ ស្រស់ ក្អក',r:"Srae sros k'ak",i:'Sawah hijau subur',n:'ស្រែ = sawah'},
    {k:'ទឹក ពេញ ស្ទឹង',r:"Tik penh s'tong",i:'Air penuh mengalir di sungai',n:'ទឹក = air'},
    {k:'ប្រជា ខ្មែរ ធ្វើស្រែ',r:'Prochea Khmer tveu srae',i:'Rakyat Khmer bertani',n:'ធ្វើ = melakukan'},
    {k:'ក្រោម ព្រះអាទិត្យ',r:'Kraom preah-atit',i:'Di bawah terik matahari',n:'ក្រោម = di bawah'},
    {k:'ដំណំ ល្អ',r:'Domnom la-aw',i:'Panen yang baik',n:'ដំណំ = panen'},
    {k:'សម្រាប់ ទាំងអស់',r:'Somrap teang ah',i:'Untuk semua orang',n:'សម្រាប់ = untuk'},
    {k:'បាយ ខ្មែរ ឆ្ងុញ',r:'Bay Khmer chhnhunh',i:'Nasi Khmer yang lezat',n:'ឆ្ងុញ = lezat'},
    {k:'ស្រ​ ល​ ាញ់​ ប​ ា​ យ',r:"S'ranh bay",i:'Mencintai nasi (kehidupan)',n:'ស្រ​ ល​ ាញ់ = mencintai'},
  ]},
  {emoji:'💫',title:'ស្នេហ៍​ ខ្ញុំ',titleIndo:'Sne Khnhom — Cintaku',singer:'Lagu Modern Khmer',desc:'Lagu cinta modern yang populer di kalangan anak muda Kamboja.',
  lyrics:[
    {k:'ស្នេហ៍ ខ្ញុំ ស្នេហ៍ អ្នក',r:"Sne khnhom sne neak",i:'Cintaku adalah cintamu',n:'ស្នេហ៍ = cinta'},
    {k:'ចិត្ត ខ្ញុំ ទ្រាំ',r:'Chet khnhom tram',i:'Hatiku bertahan',n:'ទ្រាំ = bertahan'},
    {k:'ស្រ​ ល​ ាញ់​ អ្នក​ ហ្ហ',r:"S'ranh neak",i:'Mencintaimu',n:''},
    {k:'ជ្រៅ ជ្រៅ',r:'Chrov chrov',i:'Dalam-dalam',n:'ជ្រៅ = dalam'},
    {k:'ដំណើរ ជីវិត',r:'Damnear chivit',i:'Perjalanan hidup',n:'ជីវិត = hidup/kehidupan'},
    {k:'ស្ដៅ ដៅ គ្នា',r:"S'dau dau knia",i:'Bersama-sama',n:'គ្នា = bersama'},
    {k:'ទ្រាំ ទ្រ',r:'Tram tro',i:'Sabar dan bertahan',n:'ទ្រ = menahan'},
    {k:'ជានិច្ច',r:'Chea noch',i:'Selamanya',n:''},
  ]},
  {emoji:'🎭',title:'របាំ​ អប្សរ',titleIndo:'Robam Apsara — Tari Apsara',singer:'Musik Istana Kuno',desc:'Lagu pengiring tari Apsara yang sakral, berasal dari relief Angkor Wat.',
  lyrics:[
    {k:'អប្សរ​ ស្អ​ ាត​ ស',r:"Apsara s'at sor",i:'Apsara yang cantik putih',n:'អប្សរ = bidadari'},
    {k:'ដូច​ ព្រះ​ ដែល​ ចុះ​ ស្ពាន',r:'Douch preah del choh spean',i:'Seperti dewi yang turun dari surga',n:'ព្រះ = dewa'},
    {k:'ចោម​ ផ្ការ​ ហើរ',r:'Chaom phkar haer',i:'Dikelilingi bunga bertebaran',n:'ចោម = dikelilingi'},
    {k:'ភ្លេង​ ពិណ​ ចាំ',r:'Phleng pin cham',i:'Musik kecapi mengiringi',n:'ភ្លេង = musik'},
    {k:'រំបិន​ ជ្រៅ​ ជ្រៅ',r:'Rom-pin chrov chrov',i:'Menari dalam-dalam (penuh)',n:'រំបិន = menari'},
    {k:'ដូច​ ព្រៃ​ ស្ងប់',r:"Douch prey s'ngob",i:'Seperti hutan yang tenang',n:'ព្រៃ = hutan'},
    {k:'ស្ថានសួគ៌​ ស្ថិត​ ជំ',r:'Sthan-sour sthet chom',i:'Surga ada di sini',n:'ស្ថានសួគ៌ = surga'},
    {k:'ក្នុង​ ចិត្ត​ ខ្ញុំ',r:'Knong chet khnhom',i:'Dalam hatiku',n:'ក្នុង = dalam'},
  ]},
  {emoji:'🌅',title:'ភ្នំពេញ​ ស្រឡាញ់',titleIndo:'Phnom Penh S\'ranh — Aku Cinta Phnom Penh',singer:'Lagu Cinta Ibu Kota',desc:'Lagu tentang kecintaan terhadap kota Phnom Penh yang penuh kenangan.',
  lyrics:[
    {k:'ភ្នំពេញ​ ទីក្រុង​ ស',r:"Phnom Penh ti-krong sor",i:'Phnom Penh kota yang putih bersih',n:'ទីក្រុង = kota'},
    {k:'ស្ទឹង​ ដូនពេញ​ ត្រចាំ',r:'Stong Don-Penh tra-cham',i:'Sungai Tonle Sap mengalir',n:'ស្ទឹង = sungai'},
    {k:'ខ្ញុំ​ ស្រ​ ល​ ាញ់​ ភ្នំពេញ',r:"Khnhom s'ranh Phnom Penh",i:'Aku cinta Phnom Penh',n:''},
    {k:'ជ្រៅ​ ជ្រៅ​ ក្នុង​ ចិត្ត',r:'Chrov chrov knong chet',i:'Dalam-dalam di hatiku',n:'ចិត្ត = hati'},
    {k:'ព្រះ​ ចន្ទ​ ឡើង​ ឡើង',r:'Preah-chan laeng laeng',i:'Bulan naik semakin tinggi',n:'ព្រះចន្ទ = bulan'},
    {k:'លើ​ ភ្នំ​ ពេញ​ ខ្ញុំ',r:'Leu Phnom Penh khnhom',i:'Di atas Phnom Penhku',n:''},
    {k:'ក្រុង​ ខ្ញុំ​ ស្អ​ ាត​ ណ​ ាស់',r:"Krong khnhom s'at nas",i:'Kotaku sangat indah',n:'ស្អ​ ាត = indah/cantik'},
    {k:'ជានិច្ច​ ក្នុង​ ចិត្ត',r:'Chea noch knong chet',i:'Selalu dalam hati',n:'ជានិច្ច = selalu'},
  ]},
];
const PROVERBS=[
  {k:'ដំបូងស្ករ ក្រោយជ្រក',r:"Dombong s'kor, kraoy chrok",i:'"Awalnya manis, akhirnya pahit"',m:'Jangan terlalu cepat percaya pada sesuatu yang tampak menyenangkan di awal.'},
  {k:'ទឹកជ្រោះ ចាក់ ច្រក ផ្ដើម',r:'Tik chros chak chrok phdom',i:'"Air hujan mengalir dari atas"',m:'Semua hal bermula dari asal-usulnya. Hormati sumber dari segala sesuatu.'},
  {k:'ចាស់ ដឹង ច្រើន ជាង ក្មេង',r:"Ch'as doeung chraen chea kmeng",i:'"Orang tua tahu lebih banyak dari yang muda"',m:'Hormati orang yang lebih tua karena pengalaman adalah guru terbaik.'},
  {k:'ព្រៃ ណា ពោ ដ​ ូ​ ច ព្រៃ ណោ​ ះ',r:'Prey na po douch prey noh',i:'"Hutan mana pun ada pohonnya"',m:'Di mana ada kesulitan, di sana pasti ada jalan keluarnya.'},
  {k:'មាន ប្រាក់ ទិញ ពី ត្រូវ',r:'Mean prak tinh pi trov',i:'"Punya uang beli dari yang benar"',m:'Harta yang diperoleh dengan cara halal lebih berkah dari yang tidak.'},
  {k:'ហ្វូង ត្រី ហើរ ជាមួយ',r:'Hvong trei haer chea muoy',i:'"Gerombolan ikan berenang bersama"',m:'Bersatu kita teguh, bercerai kita runtuh. Kekuatan ada pada persatuan.'},
  {k:'ដូច ទឹក ហ្វូង ករណ',r:'Douch tik hvong ko-ro-na',i:'"Seperti air mengalir"',m:'Hidup terus bergerak maju. Jangan terpaku pada masa lalu.'},
  {k:'ចិត្ត ស្អ​ ាត ជ​ ាង​ មុខ ស្អ​ ាត',r:"Chet s'at chea mok s'at",i:'"Hati yang bersih lebih baik dari wajah yang cantik"',m:'Kecantikan batin jauh lebih berharga dari kecantikan rupa.'},
  {k:'ស្ដាប ពាក្យ ចាស់ ។',r:'Sdap peak ch\'as',i:'"Dengarkanlah kata-kata orang tua"',m:'Nasihat orang tua adalah harta yang tak ternilai harganya.'},
  {k:'ការ ចេះ ដឹង ជ​ ្​ រ​ ោ​ ះ​ នៃ​ ជ​ ី​ វ​ ិ​ ត',r:'Ka cheh doeung chroh nai chivit',i:'"Pengetahuan adalah cahaya kehidupan"',m:'Ilmu pengetahuan menerangi jalan hidup dan membawa kesejahteraan.'},
  {k:'ចំណេ​ ក​ ដ​ ី​ ប​ ្​ ហែ​ ល​ ជ​ ា​ ចំ​ ណ​ ើ​ ន​ ។',r:'Chom-nek dei brhael chea chom-naen',i:'"Kehilangan tanah mungkin adalah awal kebaikan"',m:'Musibah sering kali menjadi pintu menuju berkah yang lebih besar.'},
  {k:'ប្​ ន្​ តេ​ ជ​ ្​ ន​ ី​ ជ​ ្​ ន​ ្​ ង​ ផ​ ្​ ក​ ា​ រ',r:"Bron-tej chni chnong phkar",i:'"Dibalik setiap duri ada bunga"',m:'Di balik setiap kesulitan pasti ada keindahan dan harapan.'},
];
const CULTURES=[
  {ico:'🏯',title:'Angkor Wat',desc:'Angkor Wat adalah kuil Hindu-Buddha terbesar di dunia, dibangun abad ke-12 oleh Raja Suryavarman II. Merupakan keajaiban arsitektur yang mencerminkan kosmologi Hindu. Kini menjadi simbol nasional di bendera Kamboja.',khm:'វត្តអង្គរ — Angkor Wat'},
  {ico:'👘',title:'Sampot — Pakaian Tradisional',desc:'Sampot adalah kain tradisional Kamboja yang dililitkan di pinggang. Ada berbagai jenis: Sampot Chang Kben (formal), Sampot Hol (tenun sutera), dan Sampot Phamuong. Dipakai dalam upacara resmi.',khm:'សំពត់ — Sampot'},
  {ico:'💃',title:'Tari Apsara',desc:'Tari Apsara (Robam Apsara) adalah tarian klasik Khmer yang sangat sakral. Gerakannya terinspirasi dari relief bidadari di Angkor Wat. Terdaftar sebagai Warisan Budaya Tak Benda UNESCO.',khm:'របាំអប្សរ — Tari Apsara'},
  {ico:'🎭',title:'Festival Pchum Ben',desc:'Pchum Ben adalah festival arwah leluhur selama 15 hari. Masyarakat membawa makanan ke kuil setiap pagi sebelum fajar untuk menghormati roh leluhur. Merupakan salah satu festival paling penting.',khm:'ភ្ជុំបិណ្ឌ — Pchum Ben'},
  {ico:'🍜',title:'Amok — Kuliner Khas',desc:'Amok (អាម៉ុក) adalah masakan paling khas Kamboja — ikan atau ayam dimasak dengan santan dan rempah dalam bungkusan daun pisang. Rasanya lembut dan harum. Dianggap masakan kebanggaan nasional.',khm:'អាម៉ុក — Amok'},
  {ico:'🎵',title:'Musik Pinpeat',desc:'Pinpeat adalah ansambel musik tradisional Khmer untuk upacara kuil dan tari istana. Terdiri dari xilofon kayu (roneat), gong bundar, dan seruling. Suaranya khas dan mistis.',khm:'ពិណពាទ្យ — Pinpeat'},
  {ico:'🌊',title:'Festival Bon Om Touk',desc:'Festival Air (Bon Om Touk) dirayakan saat sungai Tonle Sap berbalik arah. Lomba perahu spektakuler diadakan di Phnom Penh dengan ribuan peserta dan jutaan penonton dari seluruh negeri.',khm:'បុណ្យអុំទូក — Festival Air'},
  {ico:'📜',title:'Aksara Khmer Kuno',desc:'Aksara Khmer berasal dari aksara Pallawa India Selatan, berkembang sekitar abad ke-7 M. Merupakan salah satu sistem tulisan tertua di Asia Tenggara. Prasasti Khmer tertua bertanggal 611 M.',khm:'អក្សរខ្មែរ — Aksara Khmer'},
  {ico:'🙏',title:'Sampeah — Salam Hormat',desc:'Sampeah adalah cara menyapa dengan mengatupkan kedua tangan seperti berdoa. Semakin tinggi tangan diangkat, semakin besar rasa hormat. Di depan biksu tangan di dahi, di depan raja di atas kepala.',khm:'សំពះ — Sampeah'},
  {ico:'⛩️',title:'Kuil & Kehidupan Biksu',desc:'Hampir setiap desa di Kamboja memiliki kuil (Vot/Pagoda). Pria Khmer tradisional ditahbiskan sebagai biksu setidaknya sekali seumur hidup. Kuil adalah pusat pendidikan dan kehidupan sosial.',khm:'វត្ត — Kuil Budha'},
  {ico:'🌾',title:'Pertanian Padi',desc:'Kamboja adalah negara agraris dengan padi sebagai tanaman utama. Tonle Sap, danau air tawar terbesar di Asia Tenggara, menjadi sumber ikan dan kesuburan tanah. Panen raya dirayakan dengan meriah.',khm:'ស្រែ — Sawah Padi'},
  {ico:'🔮',title:'Kepercayaan & Animisme',desc:'Selain Buddha Theravada, masyarakat Khmer juga mempercayai Neak Ta (roh penjaga tanah) dan Arak (roh leluhur). Upacara Pithi Sena menghormati roh-roh ini agar memberikan perlindungan.',khm:'ព្រលឹង — Roh & Kepercayaan'},
];
