// ============================================================
// ALL DATA — AL JUNIOR Khmer Learning
// Pronunciation format: persis logat Khmer asli
// ============================================================

const CONSONANTS=[
  {k:'ក',l:'K',ex:'ក្ដៅ = panas',sound:'k'},
  {k:'ខ',l:'Kh',ex:'ខ្ទឹម = bawang putih',sound:'kh'},
  {k:'គ',l:'K (murni)',ex:'គោ = sapi',sound:'ko'},
  {k:'ឃ',l:'Kh (murni)',ex:'ឃ្លាំ = mengintip',sound:'kh'},
  {k:'ង',l:'Ng',ex:'ងូតទឹក = mandi',sound:'ng'},
  {k:'ច',l:'Ch',ex:'ចៃ = semut',sound:'ch'},
  {k:'ឆ',l:'Chh',ex:'ឆ្ងុយ = lezat',sound:'chh'},
  {k:'ជ',l:'Ch (murni)',ex:'ជោគជ័យ = sukses',sound:'cho'},
  {k:'ឈ',l:'Chh (murni)',ex:'ឈ្នះ = menang',sound:'chh'},
  {k:'ញ',l:'Ny',ex:'ញ៉ាំ = makan',sound:'ny'},
  {k:'ដ',l:'D',ex:'ដើម = pohon',sound:'d'},
  {k:'ឋ',l:'Th',ex:'ឋាន = tempat',sound:'th'},
  {k:'ឌ',l:'D (murni)',ex:'ឌូ = seruling',sound:'do'},
  {k:'ឍ',l:'Th (murni)',ex:'(jarang)',sound:'th'},
  {k:'ណ',l:'N',ex:'ណែ = saran',sound:'n'},
  {k:'ត',l:'T',ex:'ទួល = bukit',sound:'t'},
  {k:'ថ',l:'Th',ex:'ថ្ងៃ = hari',sound:'th'},
  {k:'ទ',l:'T (murni)',ex:'ទឹក = air',sound:'to'},
  {k:'ធ',l:'Th (murni)',ex:'ធ្លាក់ = jatuh',sound:'th'},
  {k:'ន',l:'N',ex:'នារី = wanita',sound:'n'},
  {k:'ប',l:'B/P',ex:'បាយ = nasi',sound:'b'},
  {k:'ផ',l:'Ph',ex:'ផ្ទះ = rumah',sound:'ph'},
  {k:'ព',l:'P (murni)',ex:'ពេល = waktu',sound:'p'},
  {k:'ភ',l:'Ph (murni)',ex:'ភ្លៀង = hujan',sound:'ph'},
  {k:'ម',l:'M',ex:'ម្ហូប = makanan',sound:'m'},
  {k:'យ',l:'Y',ex:'យប់ = malam',sound:'y'},
  {k:'រ',l:'R',ex:'រៀន = belajar',sound:'r'},
  {k:'ល',l:'L',ex:'លើ = di atas',sound:'l'},
  {k:'វ',l:'V/W',ex:'វ័យ = usia',sound:'v'},
  {k:'ស',l:'S',ex:'ស្នេហ៍ = cinta',sound:'s'},
  {k:'ហ',l:'H',ex:'ហូប = makan',sound:'h'},
  {k:'ឡ',l:'L (keras)',ex:'ឡើង = naik',sound:'l'},
  {k:'អ',l:'A (glottal)',ex:'អរគុណ = terima kasih',sound:'a'},
];

const VOWELS=[
  {k:'ា',l:'-aa',ex:'ចាន = piring',sound:'aa'},
  {k:'ិ',l:'-e',ex:'ទិញ = beli',sound:'e'},
  {k:'ី',l:'-ii',ex:'ស្រី = wanita',sound:'ii'},
  {k:'ុ',l:'-o',ex:'ភ្លុក = berongga',sound:'o'},
  {k:'ូ',l:'-uu',ex:'គោ = sapi',sound:'uu'},
  {k:'ួ',l:'-ua',ex:'ឃ្លួន = tubuh',sound:'ua'},
  {k:'ើ',l:'-ae',ex:'ស្ទើរ = hampir',sound:'ae'},
  {k:'ឹ',l:'-oe',ex:'ស្ទឹង = sungai',sound:'oe'},
  {k:'ែ',l:'-ae',ex:'ថ្ងែ = terang',sound:'ae'},
  {k:'ៃ',l:'-ai',ex:'ថ្ងៃ = hari',sound:'ai'},
  {k:'ោ',l:'-oo',ex:'ព្រោះ = karena',sound:'oo'},
  {k:'ៅ',l:'-au',ex:'ក្ដៅ = panas',sound:'au'},
  {k:'ំ',l:'-om',ex:'ចំ = tepat',sound:'om'},
  {k:'ាំ',l:'-am',ex:'ហ្នាំ = kebiasaan',sound:'am'},
  {k:'ះ',l:'-ah',ex:'ស្រះ = kolam',sound:'ah'},
  {k:'ៀ',l:'-ie',ex:'រៀន = belajar',sound:'ie'},
];

const DIGITS=[
  {k:'០',l:'soun (สอน)',ex:'0 = nol'},
  {k:'១',l:'muoy (มวย)',ex:'1 = satu'},
  {k:'២',l:'pii (ปี)',ex:'2 = dua'},
  {k:'៣',l:'bei (เบย)',ex:'3 = tiga'},
  {k:'៤',l:'buon (บวน)',ex:'4 = empat'},
  {k:'៥',l:'pram (ปรัม)',ex:'5 = lima'},
  {k:'៦',l:'pram-muoy',ex:'6 = enam'},
  {k:'៧',l:'pram-pii',ex:'7 = tujuh'},
  {k:'៨',l:'pram-bei',ex:'8 = delapan'},
  {k:'៩',l:'pram-buon',ex:'9 = sembilan'},
];

// ============================================================
// VOCABULARY — format: logat Khmer asli
// ============================================================
const VOCAB = {
  'Salam & Sapaan': [
    {k:'សួស្តី',r:'Suos-sdei',m:'Halo / Selamat',ex:'Dipakai kapan saja',sound:'Suos sdei'},
    {k:'ជំរាបសួរ',r:'Chomreab suor',m:'Selamat (formal)',ex:'Dipakai saat bertemu resmi',sound:'Chomreab suor'},
    {k:'ជំរាបលា',r:'Chomreab lia',m:'Selamat tinggal (formal)',ex:'Saat berpisah resmi',sound:'Chomreab lia'},
    {k:'លាហើយ',r:'Lia haoy',m:'Sampai jumpa',ex:'Sehari-hari',sound:'Lia haoy'},
    {k:'ជួបគ្នាស្អែក',r:'Chuob knia s\'aek',m:'Sampai jumpa besok',ex:'',sound:'Chuob knia s\'aek'},
    {k:'ជួបគ្នាពេលក្រោយ',r:'Chuob knia pel kraoy',m:'Sampai jumpa nanti',ex:'',sound:'Chuob knia pel kraoy'},
    {k:'បាទ',r:'Baat',m:'Ya (pria)',ex:'Dipakai pria untuk menjawab Ya',sound:'Baat'},
    {k:'ចាស',r:'Chas',m:'Ya (wanita)',ex:'Dipakai wanita untuk menjawab Ya',sound:'Chas'},
    {k:'ទេ',r:'Te',m:'Tidak',ex:'ខ្ញុំមិនទៅទេ = Saya tidak pergi',sound:'Te'},
    {k:'ខ្ញុំ',r:'Khnhom',m:'Saya / Aku',ex:'ខ្ញុំជាគ្រូ = Saya guru',sound:'Khnhom'},
    {k:'អ្នក',r:'Neak',m:'Kamu / Anda',ex:'អ្នកទៅណា = Kamu mau ke mana',sound:'Neak'},
    {k:'គាត់',r:'Koat',m:'Beliau / Dia (hormat)',ex:'',sound:'Koat'},
    {k:'នាង',r:'Neang',m:'Dia (perempuan)',ex:'',sound:'Neang'},
    {k:'យើង',r:'Yeung',m:'Kita / Kami',ex:'',sound:'Yeung'},
    {k:'ពួកគេ',r:'Puok ke',m:'Mereka',ex:'',sound:'Puok ke'},
    {k:'អរគុណ',r:'Ar-kun',m:'Terima kasih',ex:'',sound:'Ar kun'},
    {k:'អរគុណច្រើន',r:'Ar-kun chraeun',m:'Terima kasih banyak',ex:'',sound:'Ar kun chraeun'},
    {k:'សូមទោស',r:'Soum toh',m:'Maaf / Permisi',ex:'',sound:'Soum toh'},
    {k:'អត់ទោស',r:'At toh',m:'Tidak apa-apa',ex:'Balasan dari maaf',sound:'At toh'},
    {k:'ស្វាគមន៍',r:'Sveak-kom',m:'Selamat datang',ex:'',sound:'Sveak kom'},
  ],
  'Makanan': [
    {k:'ម្ហូប',r:'Mhoub',m:'Makanan / Lauk',ex:'ម្ហូបឆ្ងាញ់ = Makanan enak',sound:'Mhoub'},
    {k:'បាយ',r:'Baay',m:'Nasi',ex:'ញ៉ាំបាយ = makan nasi',sound:'Baay'},
    {k:'ញ៉ាំ',r:'Nyam',m:'Makan',ex:'ញ៉ាំបាយ = makan nasi',sound:'Nyam'},
    {k:'ហូប',r:'Houb',m:'Makan (halus)',ex:'ហូបបាយ = makan nasi (sopan)',sound:'Houb'},
    {k:'ត្រី',r:'Trei',m:'Ikan',ex:'ចំហុយត្រី = ikan kukus',sound:'Trei'},
    {k:'សាច់',r:'Sach',m:'Daging',ex:'សាច់មាន់ = daging ayam',sound:'Sach'},
    {k:'សាច់មាន់',r:'Sach moan',m:'Daging ayam',ex:'',sound:'Sach moan'},
    {k:'សាច់គោ',r:'Sach ko',m:'Daging sapi',ex:'',sound:'Sach ko'},
    {k:'សាច់ជ្រូក',r:'Sach chruk',m:'Daging babi',ex:'',sound:'Sach chruk'},
    {k:'បន្លែ',r:'Bonlae',m:'Sayuran',ex:'',sound:'Bonlae'},
    {k:'ស្ងោរ',r:'Sngaor',m:'Rebus / Masak',ex:'ស្ងោរបាយ = masak nasi',sound:'Sngaor'},
    {k:'អំបិល',r:'Ambel',m:'Garam',ex:'',sound:'Ambel'},
    {k:'ស្ករ',r:'Skor',m:'Gula',ex:'',sound:'Skor'},
    {k:'ម្រេច',r:'Mreoch',m:'Lada',ex:'',sound:'Mreoch'},
    {k:'ប្រេង',r:'Preng',m:'Minyak',ex:'',sound:'Preng'},
    {k:'ផ្លែឈើ',r:'Plae cheu',m:'Buah-buahan',ex:'',sound:'Plae cheu'},
    {k:'ចេក',r:'Cheik',m:'Pisang',ex:'',sound:'Cheik'},
    {k:'ស្វាយ',r:'Svay',m:'Mangga',ex:'',sound:'Svay'},
    {k:'ល្ហុង',r:'Lhong',m:'Pepaya',ex:'',sound:'Lhong'},
    {k:'ណាំបញ្ចុក',r:'Nam ban-chok',m:'Mie Khmer',ex:'Makanan khas sarapan',sound:'Nam ban chok'},
    {k:'អាម៉ុក',r:'A-mok',m:'Amok (kari kukus)',ex:'Masakan nasional Kamboja',sound:'A mok'},
    {k:'បបរ',r:'Babaa',m:'Bubur nasi',ex:'',sound:'Babaa'},
    {k:'ក្រូច',r:'Kroch',m:'Jeruk',ex:'',sound:'Kroch'},
    {k:'ឆ្ងាញ់',r:'Chhnhanh',m:'Enak / Lezat',ex:'ឆ្ងាញ់ណាស់ = sangat enak',sound:'Chhnhanh'},
  ],
  'Minuman': [
    {k:'ទឹក',r:'Tuk',m:'Air',ex:'ទឹកត្រជាក់ = air dingin',sound:'Tuk'},
    {k:'ទឹកត្រជាក់',r:'Tuk tra-cheak',m:'Air dingin',ex:'',sound:'Tuk tra cheak'},
    {k:'ទឹកក្តៅ',r:'Tuk k\'dao',m:'Air panas',ex:'',sound:'Tuk k\'dao'},
    {k:'ទឹកដោះគោ',r:'Tuk dos ko',m:'Susu sapi',ex:'',sound:'Tuk dos ko'},
    {k:'ទឹកអំពៅ',r:'Tuk ampou',m:'Air tebu',ex:'',sound:'Tuk ampou'},
    {k:'ទឹកក្រូច',r:'Tuk kroch',m:'Jus jeruk',ex:'',sound:'Tuk kroch'},
    {k:'ទឹកផ្លែឈើ',r:'Tuk plae cheu',m:'Jus buah',ex:'',sound:'Tuk plae cheu'},
    {k:'កាហ្វេ',r:'Ka-fei',m:'Kopi',ex:'',sound:'Ka fei'},
    {k:'តែ',r:'Tae',m:'Teh',ex:'',sound:'Tae'},
    {k:'បៀរ',r:'Bia',m:'Bir',ex:'',sound:'Bia'},
    {k:'ស្រា',r:'Sraa',m:'Minuman keras / Alkohol',ex:'',sound:'Sraa'},
    {k:'ទឹកកក',r:'Tuk kok',m:'Es batu',ex:'',sound:'Tuk kok'},
    {k:'ម្ហូបផឹក',r:'Mhoub phek',m:'Minuman',ex:'',sound:'Mhoub phek'},
    {k:'ផឹក',r:'Phek',m:'Minum',ex:'ផឹកទឹក = minum air',sound:'Phek'},
    {k:'ស្ករគ្រាប់',r:'Skor kroab',m:'Permen / Gula-gula',ex:'',sound:'Skor kroab'},
    {k:'ទឹកល្ពៅ',r:'Tuk lpou',m:'Jus labu',ex:'',sound:'Tuk lpou'},
  ],
  'Pertanyaan Harian': [
    {k:'ប៉ុន្មាន?',r:'Ponman?',m:'Berapa?',ex:'ថ្លៃប៉ុន្មាន = berapa harganya',sound:'Ponman'},
    {k:'ថ្លៃប៉ុន្មាន?',r:'Thlai ponman?',m:'Berapa harganya?',ex:'',sound:'Thlai ponman'},
    {k:'នៅឯណា?',r:'Now ae na?',m:'Di mana?',ex:'',sound:'Now ae na'},
    {k:'អ្វី?',r:'Avei?',m:'Apa?',ex:'',sound:'Avei'},
    {k:'ហេតុអ្វី?',r:'Het avei?',m:'Kenapa?',ex:'',sound:'Het avei'},
    {k:'យ៉ាងម៉េច?',r:'Yang mech?',m:'Bagaimana?',ex:'',sound:'Yang mech'},
    {k:'នៅពេលណា?',r:'Now pel na?',m:'Kapan?',ex:'',sound:'Now pel na'},
    {k:'អ្នកណា?',r:'Neak na?',m:'Siapa?',ex:'',sound:'Neak na'},
    {k:'ម៉ោងប៉ុន្មាន?',r:'Maong ponman?',m:'Jam berapa?',ex:'',sound:'Maong ponman'},
    {k:'ឈ្មោះអ្វី?',r:'Chhmua avei?',m:'Namanya apa?',ex:'',sound:'Chhmua avei'},
    {k:'អ្នកសុខសប្បាយទេ?',r:'Neak sok sabay te?',m:'Apa kabar?',ex:'',sound:'Neak sok sabay te'},
    {k:'ខ្ញុំសុខសប្បាយ',r:'Khnhom sok sabay',m:'Saya baik-baik saja',ex:'',sound:'Khnhom sok sabay'},
    {k:'ខ្ញុំមិនសូវល្អ',r:'Khnhom min sov la-aw',m:'Saya kurang baik',ex:'',sound:'Khnhom min sov la aw'},
    {k:'អ្នករស់នៅឯណា?',r:'Neak ros now ae na?',m:'Kamu tinggal di mana?',ex:'',sound:'Neak ros now ae na'},
    {k:'អ្នកធ្វើការអ្វី?',r:'Neak tveu ka avei?',m:'Kamu kerja apa?',ex:'',sound:'Neak tveu ka avei'},
    {k:'ខ្ញុំមិនយល់',r:'Khnhom min yul',m:'Saya tidak mengerti',ex:'',sound:'Khnhom min yul'},
    {k:'សូមថាម្ដងទៀត',r:'Soum tha m\'dong tiet',m:'Tolong ulangi lagi',ex:'',sound:'Soum tha m\'dong tiet'},
    {k:'ថាបណ្ដើរៗ',r:'Tha bon-daer bon-daer',m:'Tolong bicara pelan-pelan',ex:'',sound:'Tha bon daer bon daer'},
    {k:'ខ្ញុំចង់ទៅ',r:'Khnhom jong tov',m:'Saya mau pergi',ex:'',sound:'Khnhom jong tov'},
    {k:'ឆ្ងាយទេ?',r:'Chngay te?',m:'Jauh tidak?',ex:'',sound:'Chngay te'},
  ],
  'Keluarga': [
    {k:'ម្ដាយ',r:'M\'daay',m:'Ibu',ex:'ម្ដាយខ្ញុំ = Ibuku',sound:'M\'daay'},
    {k:'ឪពុក',r:'Ov-puk',m:'Ayah',ex:'ឪពុកខ្ញុំ = Ayahku',sound:'Ov puk'},
    {k:'ឪពុកម្ដាយ',r:'Ov-puk m\'daay',m:'Orang tua',ex:'',sound:'Ov puk m\'daay'},
    {k:'បង',r:'Bong',m:'Kakak',ex:'',sound:'Bong'},
    {k:'អូន',r:'Own',m:'Adik',ex:'',sound:'Own'},
    {k:'បងប្រុស',r:'Bong bros',m:'Kakak laki-laki',ex:'',sound:'Bong bros'},
    {k:'បងស្រី',r:'Bong srei',m:'Kakak perempuan',ex:'',sound:'Bong srei'},
    {k:'អូនប្រុស',r:'Own bros',m:'Adik laki-laki',ex:'',sound:'Own bros'},
    {k:'អូនស្រី',r:'Own srei',m:'Adik perempuan',ex:'',sound:'Own srei'},
    {k:'ប្ដី',r:'B\'dei',m:'Suami',ex:'',sound:'B\'dei'},
    {k:'ប្រពន្ធ',r:'Bra-pon',m:'Istri',ex:'',sound:'Bra pon'},
    {k:'កូន',r:'Koun',m:'Anak',ex:'',sound:'Koun'},
    {k:'ជីដូន',r:'Chi-don',m:'Nenek',ex:'',sound:'Chi don'},
    {k:'ជីតា',r:'Chi-ta',m:'Kakek',ex:'',sound:'Chi ta'},
    {k:'មីង',r:'Meng',m:'Tante (adik ibu/ayah)',ex:'',sound:'Meng'},
    {k:'ពូ',r:'Puu',m:'Paman (adik ayah)',ex:'',sound:'Puu'},
    {k:'ក្មួយ',r:'K\'muoy',m:'Keponakan',ex:'',sound:'K\'muoy'},
    {k:'ញាតិ',r:'Nyeat',m:'Saudara / Keluarga',ex:'',sound:'Nyeat'},
  ],
  'Tempat': [
    {k:'ផ្ទះ',r:'Pteah',m:'Rumah',ex:'ផ្ទះខ្ញុំ = rumah saya',sound:'Pteah'},
    {k:'ទីក្រុង',r:'Ti-krong',m:'Kota',ex:'',sound:'Ti krong'},
    {k:'ភូមិ',r:'Phumi',m:'Desa / Kampung',ex:'',sound:'Phumi'},
    {k:'ទីផ្សារ',r:'Ti-psar',m:'Pasar',ex:'',sound:'Ti psar'},
    {k:'ផ្លូវ',r:'Phlov',m:'Jalan',ex:'',sound:'Phlov'},
    {k:'ស្ទឹង',r:'S\'tong',m:'Sungai',ex:'',sound:'S\'tong'},
    {k:'ភ្នំ',r:'Phnom',m:'Gunung',ex:'',sound:'Phnom'},
    {k:'សមុទ្រ',r:'Sa-mot',m:'Laut',ex:'',sound:'Sa mot'},
    {k:'វត្ត',r:'Vot',m:'Kuil / Pura',ex:'',sound:'Vot'},
    {k:'ព្រៃ',r:'Prey',m:'Hutan',ex:'',sound:'Prey'},
    {k:'ស្ថានីយ',r:'S\'thaniy',m:'Stasiun / Terminal',ex:'',sound:'S\'thaniy'},
    {k:'ព្រលានយន្តហោះ',r:'Pro-lean yon-toh-hoh',m:'Bandara',ex:'',sound:'Pro lean yon toh hoh'},
    {k:'មន្ទីរពេទ្យ',r:'Mon-tir peit',m:'Rumah sakit',ex:'',sound:'Mon tir peit'},
    {k:'ធនាគារ',r:'Thona-kear',m:'Bank',ex:'',sound:'Thona kear'},
    {k:'ប្រទេស',r:'B\'ro-tes',m:'Negara',ex:'',sound:'B\'ro tes'},
    {k:'ខេត្ត',r:'Khet',m:'Provinsi',ex:'',sound:'Khet'},
    {k:'ភ្នំពេញ',r:'Phnom Penh',m:'Phnom Penh (Ibu Kota)',ex:'',sound:'Phnom Penh'},
    {k:'សៀមរាប',r:'Siem Reab',m:'Siem Reap',ex:'Kota Angkor Wat',sound:'Siem Reab'},
  ],
  'Waktu': [
    {k:'ថ្ងៃ',r:'Thngai',m:'Hari',ex:'ថ្ងៃនេះ = hari ini',sound:'Thngai'},
    {k:'ថ្ងៃនេះ',r:'Thngai nih',m:'Hari ini',ex:'',sound:'Thngai nih'},
    {k:'ម្សិលមិញ',r:'M\'sel minh',m:'Kemarin',ex:'',sound:'M\'sel minh'},
    {k:'ស្អែក',r:'S\'aek',m:'Besok',ex:'',sound:'S\'aek'},
    {k:'ខាន',r:'Khan',m:'Lusa',ex:'ខានស្អែក = lusa',sound:'Khan'},
    {k:'ព្រឹក',r:'Proek',m:'Pagi',ex:'',sound:'Proek'},
    {k:'ថ្ងៃត្រង់',r:'Thngai trong',m:'Siang / Tengah hari',ex:'',sound:'Thngai trong'},
    {k:'ល្ងាច',r:'L\'ngeach',m:'Sore',ex:'',sound:'L\'ngeach'},
    {k:'យប់',r:'Yub',m:'Malam',ex:'',sound:'Yub'},
    {k:'ឥឡូវ',r:'Ei-lov',m:'Sekarang',ex:'ឥឡូវនេះ = sekarang ini',sound:'Ei lov'},
    {k:'ម្ដង',r:'M\'dong',m:'Sekali / Dulu',ex:'',sound:'M\'dong'},
    {k:'ជារឿយៗ',r:'Chea roeuy roeuy',m:'Sering',ex:'',sound:'Chea roeuy roeuy'},
    {k:'ម៉ោង',r:'Maong',m:'Jam',ex:'ម៉ោងប៉ុន្មាន = jam berapa',sound:'Maong'},
    {k:'នាទី',r:'Nea-ti',m:'Menit',ex:'',sound:'Nea ti'},
    {k:'វិនាទី',r:'Vi-nea-ti',m:'Detik',ex:'',sound:'Vi nea ti'},
    {k:'ខែ',r:'Khae',m:'Bulan',ex:'',sound:'Khae'},
    {k:'ឆ្នាំ',r:'Chnam',m:'Tahun',ex:'',sound:'Chnam'},
    {k:'សប្ដាហ៍',r:'Sabda',m:'Minggu',ex:'',sound:'Sabda'},
    {k:'ថ្ងៃច័ន្ទ',r:'Thngai chan',m:'Senin',ex:'',sound:'Thngai chan'},
    {k:'ថ្ងៃអង្គារ',r:'Thngai ongkear',m:'Selasa',ex:'',sound:'Thngai ongkear'},
    {k:'ថ្ងៃពុធ',r:'Thngai put',m:'Rabu',ex:'',sound:'Thngai put'},
    {k:'ថ្ងៃព្រហស្បតិ៍',r:'Thngai proahoas',m:'Kamis',ex:'',sound:'Thngai proahoas'},
    {k:'ថ្ងៃសុក្រ',r:'Thngai sok',m:'Jumat',ex:'',sound:'Thngai sok'},
    {k:'ថ្ងៃសៅរ៍',r:'Thngai sao',m:'Sabtu',ex:'',sound:'Thngai sao'},
    {k:'ថ្ងៃអាទិត្យ',r:'Thngai atit',m:'Minggu',ex:'',sound:'Thngai atit'},
  ],
  'Warna': [
    {k:'ក្រហម',r:'Kra-hom',m:'Merah',ex:'ផ្ការក្រហម = bunga merah',sound:'Kra hom'},
    {k:'ខៀវ',r:'Khiev',m:'Biru',ex:'',sound:'Khiev'},
    {k:'បៃតង',r:'Bai-tong',m:'Hijau',ex:'',sound:'Bai tong'},
    {k:'លឿង',r:'Loeung',m:'Kuning',ex:'',sound:'Loeung'},
    {k:'ស',r:'Sor',m:'Putih',ex:'',sound:'Sor'},
    {k:'ខ្មៅ',r:'Khmau',m:'Hitam',ex:'',sound:'Khmau'},
    {k:'ប្រផ្លោ',r:'Bra-phlo',m:'Coklat',ex:'',sound:'Bra phlo'},
    {k:'ស្វាយ',r:'Svay',m:'Ungu',ex:'',sound:'Svay'},
    {k:'ទំពំ',r:'Tom-pom',m:'Pink / Merah muda',ex:'',sound:'Tom pom'},
    {k:'ប្រផ្អូស',r:'Bra-phaus',m:'Abu-abu',ex:'',sound:'Bra phaus'},
    {k:'ទឹកក្រូច',r:'Tuk-kroch',m:'Oranye',ex:'',sound:'Tuk kroch'},
    {k:'ពណ៌',r:'Poa',m:'Warna',ex:'',sound:'Poa'},
  ],
  'Alam': [
    {k:'ព្រះអាទិត្យ',r:'Preah atit',m:'Matahari',ex:'',sound:'Preah atit'},
    {k:'ព្រះចន្ទ',r:'Preah chan',m:'Bulan',ex:'',sound:'Preah chan'},
    {k:'ផ្ការ',r:'Phkar',m:'Bunga',ex:'',sound:'Phkar'},
    {k:'ភ្លៀង',r:'Phlieng',m:'Hujan',ex:'',sound:'Phlieng'},
    {k:'ខ្យល់',r:'Khyal',m:'Angin',ex:'',sound:'Khyal'},
    {k:'ដី',r:'Dei',m:'Tanah',ex:'',sound:'Dei'},
    {k:'ថ្ម',r:'Thma',m:'Batu',ex:'',sound:'Thma'},
    {k:'ភ្លើង',r:'Phloeng',m:'Api',ex:'',sound:'Phloeng'},
    {k:'ទឹក',r:'Tuk',m:'Air',ex:'',sound:'Tuk'},
    {k:'ក្ដៅ',r:'K\'dao',m:'Panas',ex:'',sound:'K\'dao'},
    {k:'ត្រជាក់',r:'Tra-cheak',m:'Dingin',ex:'',sound:'Tra cheak'},
    {k:'ស្ងួត',r:'S\'nguot',m:'Kering',ex:'',sound:'S\'nguot'},
  ],
  'Tubuh': [
    {k:'ក្បាល',r:'K\'bal',m:'Kepala',ex:'',sound:'K\'bal'},
    {k:'ភ្នែក',r:'Phnek',m:'Mata',ex:'',sound:'Phnek'},
    {k:'ត្រចៀក',r:'Tra-chiek',m:'Telinga',ex:'',sound:'Tra chiek'},
    {k:'ច្រមុះ',r:'Chro-moh',m:'Hidung',ex:'',sound:'Chro moh'},
    {k:'មាត់',r:'Moat',m:'Mulut',ex:'',sound:'Moat'},
    {k:'ធ្មេញ',r:'Thmeinh',m:'Gigi',ex:'',sound:'Thmeinh'},
    {k:'ដៃ',r:'Dai',m:'Tangan',ex:'',sound:'Dai'},
    {k:'ជើង',r:'Cheung',m:'Kaki',ex:'',sound:'Cheung'},
    {k:'ពោះ',r:'Puoh',m:'Perut',ex:'',sound:'Puoh'},
    {k:'ចិត្ត',r:'Chet',m:'Hati',ex:'',sound:'Chet'},
    {k:'ខ្លួន',r:'Khloun',m:'Tubuh / Diri',ex:'',sound:'Khloun'},
    {k:'ក',r:'Ko',m:'Leher',ex:'',sound:'Ko'},
    {k:'ខ្នង',r:'Khnong',m:'Punggung',ex:'',sound:'Khnong'},
    {k:'ដើមទ្រូង',r:'Daem truong',m:'Dada',ex:'',sound:'Daem truong'},
  ],
  'Emosi': [
    {k:'រីករាយ',r:'Rik-reay',m:'Bahagia / Gembira',ex:'',sound:'Rik reay'},
    {k:'ស្រឡាញ់',r:'S\'ranh',m:'Cinta / Mencintai',ex:'',sound:'S\'ranh'},
    {k:'ស្នេហ៍',r:'Sne',m:'Cinta (noun)',ex:'ស្នេហ៍ពិត = cinta sejati',sound:'Sne'},
    {k:'ខឹង',r:'Kheng',m:'Marah',ex:'',sound:'Kheng'},
    {k:'ខ្លាច',r:'Khlaach',m:'Takut',ex:'',sound:'Khlaach'},
    {k:'ព្រួយ',r:'Pruoy',m:'Khawatir',ex:'',sound:'Pruoy'},
    {k:'ឈឺចាប់',r:'Chheu-chab',m:'Sakit hati / Sedih',ex:'',sound:'Chheu chab'},
    {k:'សប្បាយ',r:'Sabay',m:'Senang / Nyaman',ex:'',sound:'Sabay'},
    {k:'ធុញ',r:'Thunh',m:'Bosan',ex:'',sound:'Thunh'},
    {k:'ងូប',r:'Ngoup',m:'Malu',ex:'',sound:'Ngoup'},
    {k:'ស្ងប់',r:'S\'ngob',m:'Tenang',ex:'',sound:'S\'ngob'},
    {k:'ឈឺ',r:'Chheu',m:'Sakit',ex:'',sound:'Chheu'},
    {k:'នឿយ',r:'Noeuy',m:'Lelah',ex:'',sound:'Noeuy'},
  ],
  'Perjalanan': [
    {k:'ទៅ',r:'Tov',m:'Pergi',ex:'',sound:'Tov'},
    {k:'មក',r:'Mok',m:'Datang',ex:'',sound:'Mok'},
    {k:'ត្រលប់',r:'Tra-lob',m:'Pulang / Kembali',ex:'',sound:'Tra lob'},
    {k:'ជិះ',r:'Chih',m:'Naik kendaraan',ex:'',sound:'Chih'},
    {k:'ដើរ',r:'Daer',m:'Jalan kaki',ex:'',sound:'Daer'},
    {k:'ឡើង',r:'Laeng',m:'Naik',ex:'',sound:'Laeng'},
    {k:'ចុះ',r:'Choh',m:'Turun',ex:'',sound:'Choh'},
    {k:'ឈប់',r:'Chhob',m:'Berhenti',ex:'',sound:'Chhob'},
    {k:'ត្រង់',r:'Trong',m:'Lurus',ex:'',sound:'Trong'},
    {k:'ស្ដាំ',r:'S\'dam',m:'Kanan',ex:'ងាកស្ដាំ = belok kanan',sound:'S\'dam'},
    {k:'ឆ្វេង',r:'Chhveng',m:'Kiri',ex:'ងាកឆ្វេង = belok kiri',sound:'Chhveng'},
    {k:'យន្តហោះ',r:'Yon-toh-hoh',m:'Pesawat',ex:'',sound:'Yon toh hoh'},
    {k:'ឡាន',r:'Lan',m:'Mobil',ex:'',sound:'Lan'},
    {k:'មោតូ',r:'Mo-to',m:'Motor',ex:'',sound:'Mo to'},
    {k:'តុ-តុក',r:'Tok-tok',m:'Tuk-tuk',ex:'Kendaraan khas Kamboja',sound:'Tok tok'},
    {k:'ទូក',r:'Tuk',m:'Perahu',ex:'',sound:'Tuk'},
    {k:'ផ្លូវ',r:'Phlov',m:'Jalan',ex:'',sound:'Phlov'},
  ],
  'Angka Dasar': [
    {k:'មួយ',r:'Muoy',m:'Satu (1)',ex:'',sound:'Muoy'},
    {k:'ពីរ',r:'Pii',m:'Dua (2)',ex:'',sound:'Pii'},
    {k:'បី',r:'Bei',m:'Tiga (3)',ex:'',sound:'Bei'},
    {k:'បួន',r:'Buon',m:'Empat (4)',ex:'',sound:'Buon'},
    {k:'ប្រាំ',r:'Pram',m:'Lima (5)',ex:'',sound:'Pram'},
    {k:'ប្រាំមួយ',r:'Pram-muoy',m:'Enam (6)',ex:'',sound:'Pram muoy'},
    {k:'ប្រាំពីរ',r:'Pram-pii',m:'Tujuh (7)',ex:'',sound:'Pram pii'},
    {k:'ប្រាំបី',r:'Pram-bei',m:'Delapan (8)',ex:'',sound:'Pram bei'},
    {k:'ប្រាំបួន',r:'Pram-buon',m:'Sembilan (9)',ex:'',sound:'Pram buon'},
    {k:'ដប់',r:'Dob',m:'Sepuluh (10)',ex:'',sound:'Dob'},
    {k:'ដប់មួយ',r:'Dob-muoy',m:'Sebelas (11)',ex:'',sound:'Dob muoy'},
    {k:'ដប់ពីរ',r:'Dob-pii',m:'Dua belas (12)',ex:'',sound:'Dob pii'},
  ],
};

// ============================================================
// PHRASES
// ============================================================
const PHRASES = [
  {cat:'Sapaan',title:'Salam & Perkenalan',rows:[
    {k:'សួស្តី!',r:'Suos-sdei!',i:'Halo!',n:'Salam paling umum'},
    {k:'ជំរាបសួរ',r:'Chomreab suor',i:'Selamat (formal)',n:'Situasi resmi'},
    {k:'អ្នកសុខសប្បាយទេ?',r:'Neak sok sabay te?',i:'Apa kabar?',n:''},
    {k:'ខ្ញុំសុខសប្បាយ អរគុណ',r:'Khnhom sok sabay, ar-kun',i:'Saya baik-baik saja, terima kasih',n:''},
    {k:'ឈ្មោះខ្ញុំ...',r:'Chhmua khnhom...',i:'Nama saya adalah...',n:''},
    {k:'ឈ្មោះអ្នកគឺអ្វី?',r:'Chhmua neak keu avei?',i:'Siapa nama kamu?',n:''},
    {k:'ខ្ញុំមកពីឥណ្ឌូនេស៊ី',r:'Khnhom mok pi In-do-ne-si',i:'Saya dari Indonesia',n:''},
    {k:'អ្នកមកពីណា?',r:'Neak mok pi na?',i:'Kamu dari mana?',n:''},
    {k:'ខ្ញុំអាយុ ... ឆ្នាំ',r:'Khnhom ayu ... chnam',i:'Saya berumur ... tahun',n:''},
    {k:'ខ្ញុំរីករាយដែលបានជួប',r:'Khnhom rik-reay del ban chuob',i:'Senang berkenalan',n:''},
    {k:'ជំរាបលា',r:'Chomreab lia',i:'Selamat tinggal (formal)',n:''},
    {k:'លាហើយ!',r:'Lia haoy!',i:'Sampai jumpa!',n:'Informal'},
  ]},
  {cat:'Kesopanan',title:'Ucapan Sopan & Terima Kasih',rows:[
    {k:'អរគុណ',r:'Ar-kun',i:'Terima kasih',n:''},
    {k:'អរគុណច្រើន',r:'Ar-kun chraeun',i:'Terima kasih banyak',n:''},
    {k:'អរគុណណាស់',r:'Ar-kun nas',i:'Terima kasih sekali',n:''},
    {k:'សូមទោស',r:'Soum toh',i:'Maaf / Permisi',n:''},
    {k:'ខ្ញុំសុំទោស',r:'Khnhom som toh',i:'Saya minta maaf',n:'Lebih serius'},
    {k:'អត់ទោស',r:'At toh',i:'Tidak apa-apa',n:'Balasan dari maaf'},
    {k:'រីករាយ',r:'Rik-reay',i:'Sama-sama',n:'Balasan terima kasih'},
    {k:'សូម',r:'Soum',i:'Tolong / Silakan',n:'Kata sopan serbaguna'},
    {k:'ជំរាបលា',r:'Chomreab lia',i:'Selamat tinggal (formal)',n:''},
    {k:'ជួបគ្នាស្អែក',r:'Chuob knia s\'aek',i:'Sampai jumpa besok',n:''},
    {k:'ប្រយ័ត្ន!',r:'Bra-yoan!',i:'Hati-hati!',n:''},
    {k:'ល្អណាស់',r:'La-aw nas',i:'Bagus sekali!',n:''},
  ]},
  {cat:'Restoran',title:'Di Restoran & Warung Makan',rows:[
    {k:'ខ្ញុំចង់ញ៉ាំ',r:'Khnhom jong nyam',i:'Saya ingin makan',n:''},
    {k:'ម្ហូបអ្វីឆ្ងាញ់?',r:'Mhoub avei chhnhanh?',i:'Makanan apa yang enak?',n:''},
    {k:'ឆ្ងាញ់ណាស់!',r:'Chhnhanh nas!',i:'Sangat enak!',n:''},
    {k:'ទឹកមួយកែវ',r:'Tuk muoy kaev',i:'Segelas air',n:''},
    {k:'ខ្ញុំជ្រើសយក...',r:'Khnhom chreuh yok...',i:'Saya pilih...',n:''},
    {k:'ចំណងជើង',r:'Cham-nong cheung',i:'Menu',n:''},
    {k:'ឆ្អែតហើយ',r:'Chhaet haoy',i:'Sudah kenyang',n:''},
    {k:'គិតថ្លៃ',r:'Kit thlai',i:'Hitung harga / Bayar',n:''},
    {k:'ថ្លៃប៉ុន្មាន?',r:'Thlai ponman?',i:'Berapa harganya?',n:''},
    {k:'ថ្លៃណាស់',r:'Thlai nas',i:'Mahal sekali',n:''},
    {k:'ថោកជាង',r:'Thoak chea',i:'Lebih murah',n:''},
    {k:'ខ្ញុំគ្មានប្រាក់គ្រប់',r:'Khnhom kmean brak kroup',i:'Saya tidak punya cukup uang',n:''},
  ]},
  {cat:'Belanja',title:'Belanja di Pasar',rows:[
    {k:'ខ្ញុំចង់ទិញ',r:'Khnhom jong tinh',i:'Saya mau beli',n:''},
    {k:'ថ្លៃប៉ុន្មាន?',r:'Thlai ponman?',i:'Berapa harganya?',n:''},
    {k:'ថ្លៃណាស់',r:'Thlai nas',i:'Mahal sekali',n:''},
    {k:'ថោក',r:'Thoak',i:'Murah',n:''},
    {k:'ថ្លៃ',r:'Thlai',i:'Mahal',n:''},
    {k:'បញ្ចុះតម្លៃ',r:'Ban-choh dom-lai',i:'Diskon / Kurang harga',n:''},
    {k:'ខ្ញុំយក',r:'Khnhom yok',i:'Saya ambil / beli',n:''},
    {k:'ខ្ញុំមិនយក',r:'Khnhom min yok',i:'Saya tidak jadi beli',n:''},
    {k:'មានទំហំផ្សេង?',r:'Mean tom-hom pseng?',i:'Ada ukuran lain?',n:''},
    {k:'ប្រាក់',r:'Brak',m:'Uang',n:''},
    {k:'ប្រាក់រៀល',r:'Brak riel',i:'Uang Riel (Kamboja)',n:'Mata uang Kamboja'},
    {k:'ប្រាក់ដុល្លារ',r:'Brak dol-lar',i:'Uang Dolar',n:''},
  ]},
  {cat:'Kesehatan',title:'Kesehatan & Darurat',rows:[
    {k:'ខ្ញុំឈឺ',r:'Khnhom chheu',i:'Saya sakit',n:''},
    {k:'ខ្ញុំត្រូវការវេជ្ជបណ្ឌិត',r:'Khnhom trov kar veach-bon-det',i:'Saya butuh dokter',n:''},
    {k:'ឈឺក្បាល',r:'Chheu k\'bal',i:'Sakit kepala',n:''},
    {k:'ឈឺពោះ',r:'Chheu puoh',i:'Sakit perut',n:''},
    {k:'ក្អួត',r:'K\'uot',i:'Muntah',n:''},
    {k:'គ្រុនក្ដៅ',r:'Krun k\'dao',i:'Demam',n:''},
    {k:'ជួយខ្ញុំផង!',r:'Chuoy khnhom phong!',i:'Tolong bantu saya!',n:'Darurat'},
    {k:'ហៅប៉ូលីស!',r:'Hao po-lis!',i:'Panggil polisi!',n:''},
    {k:'ថ្នាំ',r:'Thnam',i:'Obat',n:''},
    {k:'ពេទ្យ',r:'Peit',i:'Dokter',n:''},
    {k:'មន្ទីរពេទ្យ',r:'Mon-tir peit',i:'Rumah sakit',n:''},
    {k:'គ្រោះថ្នាក់',r:'Kruos-thnak',i:'Bahaya / Kecelakaan',n:''},
  ]},
  {cat:'Perjalanan',title:'Perjalanan & Transportasi',rows:[
    {k:'ខ្ញុំចង់ទៅ...',r:'Khnhom jong tov...',i:'Saya mau pergi ke...',n:''},
    {k:'ឆ្ងាយទេ?',r:'Chngay te?',i:'Jauh tidak?',n:''},
    {k:'ទៅ...ដោយរបៀបណា?',r:'Tov...daoy ro-beb na?',i:'Ke...caranya bagaimana?',n:''},
    {k:'ត្រង់',r:'Trong',i:'Lurus',n:''},
    {k:'ងាកស្ដាំ',r:'Ngeak s\'dam',i:'Belok kanan',n:''},
    {k:'ងាកឆ្វេង',r:'Ngeak chhveng',i:'Belok kiri',n:''},
    {k:'ជិះតាក់ស៊ី',r:'Chih tak-si',i:'Naik taksi',n:''},
    {k:'ជិះតុ-តុក',r:'Chih tok-tok',i:'Naik tuk-tuk',n:''},
    {k:'ចុះនៅទីនេះ',r:'Choh now ti nih',i:'Turun di sini',n:''},
    {k:'ស្ថានីយរថភ្លើង',r:'S\'thaniy rot-phloeng',i:'Stasiun kereta',n:''},
    {k:'ប្រដេញ',r:'Bra-denh',i:'Kejar / Cepat',n:''},
    {k:'ធ្វើដំណើរ',r:'Tveu dom-noeuy',i:'Bepergian',n:''},
  ]},
];

// ============================================================
// NUMBERS COMPLETE — dari 0 sampai 1 juta berurut
// ============================================================
const NUMBERS = [
  // 0-9
  {n:'0',k:'សូន្យ',r:'Soun',m:'Nol'},
  {n:'1',k:'មួយ',r:'Muoy',m:'Satu'},
  {n:'2',k:'ពីរ',r:'Pii',m:'Dua'},
  {n:'3',k:'បី',r:'Bei',m:'Tiga'},
  {n:'4',k:'បួន',r:'Buon',m:'Empat'},
  {n:'5',k:'ប្រាំ',r:'Pram',m:'Lima'},
  {n:'6',k:'ប្រាំមួយ',r:'Pram-muoy',m:'Enam'},
  {n:'7',k:'ប្រាំពីរ',r:'Pram-pii',m:'Tujuh'},
  {n:'8',k:'ប្រាំបី',r:'Pram-bei',m:'Delapan'},
  {n:'9',k:'ប្រាំបួន',r:'Pram-buon',m:'Sembilan'},
  // 10-19
  {n:'10',k:'ដប់',r:'Dob',m:'Sepuluh'},
  {n:'11',k:'ដប់មួយ',r:'Dob-muoy',m:'Sebelas'},
  {n:'12',k:'ដប់ពីរ',r:'Dob-pii',m:'Dua belas'},
  {n:'13',k:'ដប់បី',r:'Dob-bei',m:'Tiga belas'},
  {n:'14',k:'ដប់បួន',r:'Dob-buon',m:'Empat belas'},
  {n:'15',k:'ដប់ប្រាំ',r:'Dob-pram',m:'Lima belas'},
  {n:'16',k:'ដប់ប្រាំមួយ',r:'Dob-pram-muoy',m:'Enam belas'},
  {n:'17',k:'ដប់ប្រាំពីរ',r:'Dob-pram-pii',m:'Tujuh belas'},
  {n:'18',k:'ដប់ប្រាំបី',r:'Dob-pram-bei',m:'Delapan belas'},
  {n:'19',k:'ដប់ប្រាំបួន',r:'Dob-pram-buon',m:'Sembilan belas'},
  // 20-29
  {n:'20',k:'ម្ភៃ',r:'Mpei',m:'Dua puluh'},
  {n:'21',k:'ម្ភៃមួយ',r:'Mpei-muoy',m:'Dua puluh satu'},
  {n:'22',k:'ម្ភៃពីរ',r:'Mpei-pii',m:'Dua puluh dua'},
  {n:'23',k:'ម្ភៃបី',r:'Mpei-bei',m:'Dua puluh tiga'},
  {n:'24',k:'ម្ភៃបួន',r:'Mpei-buon',m:'Dua puluh empat'},
  {n:'25',k:'ម្ភៃប្រាំ',r:'Mpei-pram',m:'Dua puluh lima'},
  {n:'26',k:'ម្ភៃប្រាំមួយ',r:'Mpei-pram-muoy',m:'Dua puluh enam'},
  {n:'27',k:'ម្ភៃប្រាំពីរ',r:'Mpei-pram-pii',m:'Dua puluh tujuh'},
  {n:'28',k:'ម្ភៃប្រាំបី',r:'Mpei-pram-bei',m:'Dua puluh delapan'},
  {n:'29',k:'ម្ភៃប្រាំបួន',r:'Mpei-pram-buon',m:'Dua puluh sembilan'},
  // 30-90
  {n:'30',k:'សាមសិប',r:'Saam-seb',m:'Tiga puluh'},
  {n:'31',k:'សាមសិបមួយ',r:'Saam-seb-muoy',m:'Tiga puluh satu'},
  {n:'40',k:'សែសិប',r:'Sae-seb',m:'Empat puluh'},
  {n:'41',k:'សែសិបមួយ',r:'Sae-seb-muoy',m:'Empat puluh satu'},
  {n:'50',k:'ហាសិប',r:'Haa-seb',m:'Lima puluh'},
  {n:'51',k:'ហាសិបមួយ',r:'Haa-seb-muoy',m:'Lima puluh satu'},
  {n:'60',k:'ហុកសិប',r:'Hok-seb',m:'Enam puluh'},
  {n:'70',k:'ចិតសិប',r:'Chet-seb',m:'Tujuh puluh'},
  {n:'80',k:'ប៉ែតសិប',r:'Paet-seb',m:'Delapan puluh'},
  {n:'90',k:'កៅសិប',r:'Kau-seb',m:'Sembilan puluh'},
  // 100+
  {n:'100',k:'មួយរយ',r:'Muoy roi',m:'Seratus'},
  {n:'200',k:'ពីររយ',r:'Pii roi',m:'Dua ratus'},
  {n:'300',k:'បីរយ',r:'Bei roi',m:'Tiga ratus'},
  {n:'400',k:'បួនរយ',r:'Buon roi',m:'Empat ratus'},
  {n:'500',k:'ប្រាំរយ',r:'Pram roi',m:'Lima ratus'},
  {n:'600',k:'ប្រាំមួយរយ',r:'Pram-muoy roi',m:'Enam ratus'},
  {n:'700',k:'ប្រាំពីររយ',r:'Pram-pii roi',m:'Tujuh ratus'},
  {n:'800',k:'ប្រាំបីរយ',r:'Pram-bei roi',m:'Delapan ratus'},
  {n:'900',k:'ប្រាំបួនរយ',r:'Pram-buon roi',m:'Sembilan ratus'},
  // 1000+
  {n:'1.000',k:'មួយពាន់',r:'Muoy poan',m:'Seribu'},
  {n:'2.000',k:'ពីរពាន់',r:'Pii poan',m:'Dua ribu'},
  {n:'5.000',k:'ប្រាំពាន់',r:'Pram poan',m:'Lima ribu'},
  {n:'10.000',k:'មួយម៉ឺន',r:'Muoy meun',m:'Sepuluh ribu'},
  {n:'20.000',k:'ពីរម៉ឺន',r:'Pii meun',m:'Dua puluh ribu'},
  {n:'50.000',k:'ប្រាំម៉ឺន',r:'Pram meun',m:'Lima puluh ribu'},
  {n:'100.000',k:'មួយសែន',r:'Muoy saen',m:'Seratus ribu'},
  {n:'500.000',k:'ប្រាំសែន',r:'Pram saen',m:'Lima ratus ribu'},
  {n:'1.000.000',k:'មួយលាន',r:'Muoy lean',m:'Satu juta'},
];

const NUM_SECTIONS = [
  {title:'🔢 Angka 0 — 9 (Dasar)', range:[0,9]},
  {title:'🔢 Angka 10 — 19', range:[10,19]},
  {title:'🔢 Angka 20 — 29', range:[20,29]},
  {title:'🔢 Angka 30 — 99 (Puluhan)', range:[30,39]},
  {title:'🔢 Angka 100 — 900 (Ratusan)', range:[40,48]},
  {title:'🔢 Angka 1.000 ke atas', range:[49,57]},
];

// ============================================================
// GRAMMAR
// ============================================================
const GRAMMAR = [
  {ico:'🔤',title:'Pola Kalimat (SPO)',body:'Bahasa Khmer menggunakan pola <strong>Subjek – Kata Kerja – Objek</strong>, persis seperti Indonesia. Tidak ada konjugasi kata kerja.',k:'ខ្ញុំញ៉ាំបាយ',r:'Khnhom nyam baay',i:'Saya makan nasi'},
  {ico:'⏰',title:'Menyatakan Waktu',body:'Kata kerja tidak berubah. Waktu dinyatakan dengan kata tambahan: <strong>បាន (ban)</strong> = sudah, <strong>នឹង (neng)</strong> = akan, <strong>កំពុង (kom-pong)</strong> = sedang.',k:'ខ្ញុំកំពុងរៀន',r:'Khnhom kom-pong rien',i:'Saya sedang belajar'},
  {ico:'🤝',title:'Kata Ganti Orang',body:'<strong>ខ្ញុំ (khnhom)</strong> = Saya, <strong>អ្នក (neak)</strong> = Kamu, <strong>លោក (lok)</strong> = Bapak, <strong>នាង (neang)</strong> = Dia perempuan, <strong>គាត់ (koat)</strong> = Beliau.',k:'លោកជានរណា?',r:'Lok chea no-ro-na?',i:'Bapak siapa?'},
  {ico:'❓',title:'Kalimat Tanya',body:'Tambahkan <strong>ទេ (te)</strong> di akhir untuk ya/tidak. Kata tanya: <strong>ហេតុអ្វី (het avei)</strong>=kenapa, <strong>ណា (na)</strong>=mana, <strong>ប៉ុន្មាន (ponman)</strong>=berapa.',k:'អ្នកទៅទេ?',r:'Neak tov te?',i:'Kamu pergi tidak?'},
  {ico:'🚫',title:'Kalimat Negatif',body:'Gunakan <strong>មិន (min)</strong> sebelum kata kerja dan <strong>ទេ (te)</strong> di akhir kalimat.',k:'ខ្ញុំមិនទៅទេ',r:'Khnhom min tov te',i:'Saya tidak pergi'},
  {ico:'📏',title:'Kata Sifat',body:'Kata sifat diletakkan <strong>setelah</strong> kata benda. Contoh: ផ្ទះធំ = rumah besar, ក្មេងស្អាត = anak cantik.',k:'ផ្ទះធំ',r:'Pteah thom',i:'Rumah besar'},
  {ico:'🎭',title:'Tingkat Kesopanan',body:'Ada bahasa rakyat dan bahasa istana. Contoh: "makan" = <strong>ញ៉ាំ (nyam)</strong> untuk sehari-hari, <strong>ហូប (houb)</strong> lebih sopan, <strong>ស្វាយ (svay)</strong> untuk raja.',k:'គាត់ហូបអាហារ',r:'Koat houb ahaa',i:'Beliau makan (sopan)'},
  {ico:'🔗',title:'Kata Penghubung',body:'<strong>និង (ning)</strong>=dan, <strong>ឬ (reu)</strong>=atau, <strong>ប៉ុន្តែ (bontae)</strong>=tapi, <strong>ព្រោះ (pruoh)</strong>=karena, <strong>ដូច្នេះ (doch-nih)</strong>=jadi.',k:'ខ្ញុំនិងអ្នក',r:'Khnhom ning neak',i:'Saya dan kamu'},
  {ico:'➕',title:'Menghitung & Pengukuran',body:'Kata klasifikator wajib: <strong>នាក់ (neak)</strong>=orang, <strong>ក្បាល (k\'bal)</strong>=hewan berkepala, <strong>ដើម (daem)</strong>=pohon, <strong>គ្រាប់ (kroab)</strong>=biji.',k:'ក្មេងពីរនាក់',r:'Kmeng pii neak',i:'Dua orang anak'},
];

// ============================================================
// SONGS
// ============================================================
const SONGS = [
  {emoji:'🌸',title:'ស្រីគ្រឹស្ថ',titleIndo:'Srey Kres — Gadis Kristal',singer:'Ros Sereysothea · Era 1960an',desc:'Lagu cinta klasik era emas musik Khmer, paling dicintai sepanjang masa.',
  lyrics:[
    {k:'ស្រីគ្រឹស្ថ ស្អាតពណ៌ស',r:'Srey kres, s\'at poa sor',i:'Gadis kristal, cantik berkulit putih',n:'ស្រី=gadis, ស្អាត=cantik'},
    {k:'ភ្នែកស្រស់ ដូចផ្ការ',r:'Phnek sros, douch phkar',i:'Mata indah bagai bunga',n:'ភ្នែក=mata, ដូច=seperti'},
    {k:'ចិត្តខ្ញុំ ស្រឡាញ់នាង',r:'Chet khnhom, s\'ranh neang',i:'Hatiku mencintainya',n:'ចិត្ត=hati, ស្រឡាញ់=cinta'},
    {k:'ស្នើសុំ ចងស្រស់',r:'S\'noe-som, chong sros',i:'Memohon untuk bersatu',n:'ស្នើ=memohon'},
    {k:'ខ្ញុំស្រឡាញ់អ្នក',r:'Khnhom s\'ranh neak',i:'Aku mencintaimu',n:'ស្រឡាញ់=cinta'},
    {k:'ជារចិត្តពិត',r:'Chea ro chet pit',i:'Dengan hati yang tulus',n:'ពិត=tulus/benar'},
    {k:'ពុំចង់ឃ្លាតចាក',r:'Pom chong khloat chak',i:'Tidak mau berpisah',n:'ឃ្លាត=berpisah'},
    {k:'គ្នារហូតដល់ស្លាប់',r:'Knia rohout dal slap',i:'Bersama hingga akhir hayat',n:'ស្លាប់=mati'},
  ]},
  {emoji:'🌙',title:'ព្រះចន្ទ',titleIndo:'Preah Chan — Oh Bulan',singer:'Sinn Sisamouth · Raja Musik Khmer',desc:'Lagu romantis paling ikonik dari legenda musik Kamboja.',
  lyrics:[
    {k:'ព្រះចន្ទ ពេញ រះ',r:'Preah chan, penh reah',i:'Bulan purnama bersinar',n:'ព្រះចន្ទ=bulan'},
    {k:'លើ ទឹក ប្រណ្ដៅ',r:'Leu tuk, bron-dau',i:'Di atas air yang tenang',n:'ទឹក=air'},
    {k:'ខ្ញុំ នឹក ដល់ ម្ង',r:'Khnhom nek, dal mong',i:'Aku teringat kenangan',n:'នឹក=teringat'},
    {k:'ផ្ការ ឈ្លក់',r:'Phkar chhlok',i:'Bunga mekar harum',n:'ផ្ការ=bunga'},
    {k:'ត្រជាក់ ព្រឹក',r:'Tra-cheak proek',i:'Sejuk di pagi hari',n:'ត្រជាក់=sejuk'},
    {k:'ស្នេហ៍ ពិត ពុំ ស្លាប់',r:'Sne pit, pom slap',i:'Cinta sejati tidak mati',n:'ស្នេហ៍=cinta'},
    {k:'ជានិច្ចកាល',r:'Chea noch kal',i:'Untuk selamanya',n:'និច្ច=abadi'},
    {k:'ស្រឡាញ់ ជានិច្ច',r:'S\'ranh chea noch',i:'Mencintai selamanya',n:''},
  ]},
  {emoji:'🏯',title:'វត្តអង្គរ',titleIndo:'Vot Angkor — Keagungan Angkor',singer:'Lagu Kebanggaan Nasional',desc:'Hymne keagungan Angkor Wat, simbol kejayaan peradaban Khmer.',
  lyrics:[
    {k:'អង្គរវត្ត ល្បីល្បាញ',r:'Angkor Vot, lbei lbanh',i:'Angkor Wat yang termasyhur',n:'ល្បី=terkenal'},
    {k:'បេតិកភណ្ឌ ខ្មែររបស់',r:'Betik-phon, Khmer robos',i:'Warisan milik bangsa Khmer',n:''},
    {k:'ប្រជាខ្មែរ ជាទីស្រឡាញ់',r:'Prochea Khmer, chea ti s\'ranh',i:'Rakyat Khmer yang tercinta',n:'ប្រជា=rakyat'},
    {k:'រីករំចម្រើន ជានិច្ច',r:'Rik-rom cham-roeun, chea noch',i:'Berkembang maju selamanya',n:''},
    {k:'ខ្មែររស់ ជានិច្ចនិរន្ដ',r:'Khmer ros, chea noch nirant',i:'Khmer hidup abadi',n:'រស់=hidup'},
    {k:'ជាតិ ខ្មែរ រុងរឿង',r:'Cheat Khmer, rong-roeung',i:'Bangsa Khmer berjaya',n:'ជាតិ=bangsa'},
    {k:'ស្រឡាញ់ ប្រទេស',r:'S\'ranh bra-tes',i:'Mencintai negara',n:''},
    {k:'ជារ​ ដ​ ណ​ ើ​ រ',r:'Chea da-noeuy',i:'Sebagai perjalanan',n:''},
  ]},
  {emoji:'🌺',title:'ដំណើរស្នេហ៍',titleIndo:'Damnear Sne — Perjalanan Cinta',singer:'Pop Modern Khmer',desc:'Balada romantis tentang perjalanan dua insan yang saling mencintai.',
  lyrics:[
    {k:'ដំណើរស្នេហ៍ ដែលយើងហើរ',r:'Damnear sne, del yeung haer',i:'Perjalanan cinta yang kita lalui',n:'ដំណើរ=perjalanan'},
    {k:'ពីព្រឹក ដល់យប់',r:'Pi proek, dal yub',i:'Dari pagi hingga malam',n:'ព្រឹក=pagi, យប់=malam'},
    {k:'ជាមួយ គ្នា ជានិច្ច',r:'Chea muoy, knia chea noch',i:'Bersama selamanya',n:'ជាមួយ=bersama'},
    {k:'ស្នេហ៍ ពិត ពុំ ស្លាប់',r:'Sne pit, pom slap',i:'Cinta sejati tidak mati',n:''},
    {k:'ចាប់ ដៃ ដើរ ជាមួយ',r:'Chab dai, daer chea muoy',i:'Bergandengan tangan',n:'ចាប់=pegang'},
    {k:'ទៅ ចុង ផ្លូវ ស្នេហ៍',r:'Tov chong, phlov sne',i:'Menuju ujung jalan cinta',n:'ចុង=ujung'},
    {k:'ស្នេហ៍ ស្ងប់ ស្ងាត់',r:'Sne s\'ngob s\'ngat',i:'Cinta yang tenang damai',n:''},
    {k:'ជា​ ជីវ​ ិ​ ត',r:'Chea chi-vit',i:'Adalah kehidupan',n:'ជីវិត=kehidupan'},
  ]},
  {emoji:'🌾',title:'ស្រែ',titleIndo:'Srae — Sawah',singer:'Lagu Tradisional',desc:'Lagu tentang kehidupan petani Khmer yang penuh kerja keras.',
  lyrics:[
    {k:'ស្រែ ស្រស់ ក្អក',r:'Srae, sros k\'ak',i:'Sawah subur dan hijau',n:'ស្រែ=sawah'},
    {k:'ទឹក ពេញ ស្ទឹង',r:'Tuk, penh s\'tong',i:'Air penuh di sungai',n:'ទឹក=air'},
    {k:'ប្រជា ខ្មែរ ធ្វើស្រែ',r:'Prochea Khmer, tveu srae',i:'Rakyat Khmer bertani',n:'ធ្វើ=melakukan'},
    {k:'ក្រោម ព្រះអាទិត្យ',r:'Kraom, preah atit',i:'Di bawah matahari',n:'ក្រោម=di bawah'},
    {k:'ដំណំ ល្អ',r:'Dom-nom la-aw',i:'Panen yang bagus',n:'ដំណំ=panen'},
    {k:'សម្រាប់ ទាំងអស់',r:'Som-rab, teang ah',i:'Untuk semua orang',n:'សម្រាប់=untuk'},
    {k:'បាយ ខ្មែរ ឆ្ងាញ់',r:'Baay Khmer, chhnhanh',i:'Nasi Khmer yang enak',n:'ឆ្ងាញ់=enak'},
    {k:'ស្រ​ ល​ ា​ ញ់​ ជ​ ីវ​ ិ​ ត',r:'S\'ranh chi-vit',i:'Mencintai kehidupan',n:''},
  ]},
  {emoji:'💫',title:'ស្នេហ៍ ខ្ញុំ',titleIndo:'Sne Khnhom — Cintaku',singer:'Lagu Pop Khmer Modern',desc:'Lagu cinta modern yang populer di kalangan anak muda Kamboja.',
  lyrics:[
    {k:'ស្នេហ៍ ខ្ញុំ ស្នេហ៍ អ្នក',r:'Sne khnhom, sne neak',i:'Cintaku adalah cintamu',n:'ស្នេហ៍=cinta'},
    {k:'ចិត្ត ខ្ញុំ ទ្រាំ',r:'Chet khnhom, tram',i:'Hatiku bertahan',n:'ទ្រាំ=bertahan'},
    {k:'ស្រឡាញ់ អ្នក ជ្រៅ',r:'S\'ranh neak, chrov',i:'Mencintaimu dalam-dalam',n:'ជ្រៅ=dalam'},
    {k:'ដំណើរ ជីវិត',r:'Damnear chi-vit',i:'Perjalanan hidup',n:'ជីវិត=kehidupan'},
    {k:'ទ្រាំ ជាមួយ',r:'Tram chea muoy',i:'Bertahan bersama',n:''},
    {k:'ជានិច្ច',r:'Chea noch',i:'Selamanya',n:''},
    {k:'ចិត្ត ល្អ',r:'Chet la-aw',i:'Hati yang baik',n:'ល្អ=baik'},
    {k:'ស្រឡាញ់ ជានិច្ច',r:'S\'ranh chea noch',i:'Mencintai selamanya',n:''},
  ]},
  {emoji:'🎭',title:'របាំអប្សរ',titleIndo:'Robam Apsara — Tari Bidadari',singer:'Musik Istana Kuno',desc:'Musik pengiring tari Apsara sakral dari relief Angkor Wat.',
  lyrics:[
    {k:'អប្សរ ស្អាត ស',r:'Apsara, s\'at sor',i:'Bidadari cantik putih bersih',n:'អប្សរ=bidadari surgawi'},
    {k:'ដូច ព្រះ ដែល ចុះ',r:'Douch preah, del choh',i:'Bagai dewi yang turun',n:'ព្រះ=dewa/suci'},
    {k:'ចោម ផ្ការ ហើរ',r:'Chaom phkar, haer',i:'Dikelilingi bunga melayang',n:'ចោម=dikelilingi'},
    {k:'ភ្លេង ពិណ ចាំ',r:'Phloeng pin, cham',i:'Musik kecapi mengiringi',n:'ភ្លេង=musik'},
    {k:'រំបិន ជ្រៅ ជ្រៅ',r:'Rom-bin, chrov chrov',i:'Menari dengan penuh penghayatan',n:''},
    {k:'ដូច ព្រៃ ស្ងប់',r:'Douch prey, s\'ngob',i:'Seperti hutan yang sunyi',n:'ព្រៃ=hutan'},
    {k:'ស្ថានសួគ៌ ស្ថិត',r:'S\'than-suor, sthet',i:'Surga bersemayam',n:'ស្ថានសួគ៌=surga'},
    {k:'ក្នុង ចិត្ត ខ្ញុំ',r:'Knong chet khnhom',i:'Di dalam hatiku',n:'ក្នុង=di dalam'},
  ]},
  {emoji:'🌅',title:'ភ្នំពេញ ស្រឡាញ់',titleIndo:'Phnom Penh S\'ranh — Aku Cinta Phnom Penh',singer:'Lagu Cinta Ibu Kota',desc:'Lagu tentang kecintaan pada kota Phnom Penh yang penuh kenangan.',
  lyrics:[
    {k:'ភ្នំពេញ ទីក្រុង ស',r:'Phnom Penh, ti-krong sor',i:'Phnom Penh kota yang bersih',n:'ទីក្រុង=kota'},
    {k:'ស្ទឹងទន្លេ ត្រចាំ',r:'S\'tong tonle, tra-cham',i:'Sungai Tonle mengalir',n:'ស្ទឹង=sungai'},
    {k:'ខ្ញុំ ស្រឡាញ់ ភ្នំពេញ',r:'Khnhom s\'ranh, Phnom Penh',i:'Aku cinta Phnom Penh',n:''},
    {k:'ជ្រៅ ជ្រៅ ក្នុង ចិត្ត',r:'Chrov chrov, knong chet',i:'Dalam-dalam di hatiku',n:''},
    {k:'ព្រះ ចន្ទ ឡើង ឡើង',r:'Preah chan, laeng laeng',i:'Bulan naik semakin tinggi',n:''},
    {k:'លើ ភ្នំ ពេញ',r:'Leu Phnom Penh',i:'Di atas Phnom Penh',n:'លើ=di atas'},
    {k:'ក្រុង ខ្ញុំ ស្អាត',r:'Krong khnhom, s\'at',i:'Kotaku yang indah',n:'ក្រុង=kota'},
    {k:'ជានិច្ច ក្នុង ចិត្ត',r:'Chea noch, knong chet',i:'Selalu dalam hati',n:''},
  ]},
];

// ============================================================
// PROVERBS
// ============================================================
const PROVERBS = [
  {k:'ដំបូងស្ករ ក្រោយជ្រក',r:'Dom-bong skor, kraoy chrok',i:'"Awalnya manis, akhirnya pahit"',m:'Jangan terlalu cepat percaya sesuatu yang tampak menyenangkan di awal.'},
  {k:'ចាស់ ដឹង ច្រើន ជាង ក្មេង',r:'Ch\'as doeung chraeun, chea kmeng',i:'"Orang tua tahu lebih banyak"',m:'Hormati orang yang lebih tua karena pengalaman adalah guru terbaik.'},
  {k:'ចិត្ត ស្អាត ជាង មុខ ស្អាត',r:'Chet s\'at, chea mok s\'at',i:'"Hati bersih lebih baik dari wajah cantik"',m:'Kecantikan batin jauh lebih berharga dari kecantikan rupa.'},
  {k:'ស្ដាប់ ពាក្យ ចាស់',r:'S\'dab peak ch\'as',i:'"Dengarkanlah kata-kata orang tua"',m:'Nasihat orang tua adalah harta yang tak ternilai.'},
  {k:'ការ ចេះ ដឹង ជ្រោះ ជីវិត',r:'Ka cheh doeung, chroh chi-vit',i:'"Pengetahuan adalah cahaya kehidupan"',m:'Ilmu pengetahuan menerangi jalan hidup.'},
  {k:'ហ្វូង ត្រី ហើរ ជាមួយ',r:'Hvong trei, haer chea muoy',i:'"Gerombolan ikan berenang bersama"',m:'Kekuatan ada pada persatuan. Bersatu kita teguh.'},
  {k:'ទឹក ជ្រោះ ចាក់ ច្រក',r:'Tuk chroh, chak chrok',i:'"Air hujan mengalir dari atas"',m:'Semua hal bermula dari asal-usulnya.'},
  {k:'ប្ន្តេជ្នី ជ្ន្ង ផ្ការ',r:'Bron-tej chni, chnong phkar',i:'"Di balik duri ada bunga"',m:'Di balik setiap kesulitan pasti ada keindahan.'},
];

// ============================================================
// CULTURE
// ============================================================
const CULTURES = [
  {ico:'🏯',title:'Angkor Wat',desc:'Kuil Hindu-Buddha terbesar di dunia, dibangun abad ke-12 oleh Raja Suryavarman II. Menjadi simbol nasional di bendera Kamboja.',khm:'វត្តអង្គរ — Angkor Wat'},
  {ico:'👘',title:'Sampot — Pakaian Tradisional',desc:'Kain tradisional Kamboja yang dililitkan di pinggang. Ada jenis Sampot Hol (tenun sutra) untuk upacara resmi.',khm:'សំពត់ — Sampot'},
  {ico:'💃',title:'Tari Apsara',desc:'Tarian klasik Khmer yang sangat sakral, terinspirasi dari relief bidadari di Angkor Wat. Terdaftar UNESCO.',khm:'របាំអប្សរ — Tari Apsara'},
  {ico:'🎭',title:'Festival Pchum Ben',desc:'Festival arwah leluhur selama 15 hari. Masyarakat membawa makanan ke kuil sebelum fajar untuk menghormati roh leluhur.',khm:'ភ្ជុំបិណ្ឌ — Pchum Ben'},
  {ico:'🍜',title:'Amok — Kuliner Khas',desc:'Masakan paling khas Kamboja — ikan kukus dengan santan dan rempah dalam bungkusan daun pisang. Masakan kebanggaan nasional.',khm:'អាម៉ុក — Amok'},
  {ico:'🎵',title:'Musik Pinpeat',desc:'Ansambel musik tradisional Khmer untuk upacara kuil. Terdiri dari xilofon kayu, gong bundar, dan seruling.',khm:'ពិណពាទ្យ — Pinpeat'},
  {ico:'🌊',title:'Festival Bon Om Touk',desc:'Festival Air saat sungai Tonle Sap berbalik arah. Lomba perahu spektakuler diadakan di Phnom Penh.',khm:'បុណ្យអុំទូក — Festival Air'},
  {ico:'🙏',title:'Sampeah — Salam Hormat',desc:'Menyapa dengan mengatupkan tangan seperti berdoa. Semakin tinggi tangan diangkat, semakin besar rasa hormat.',khm:'សំពះ — Sampeah'},
  {ico:'📜',title:'Aksara Khmer Kuno',desc:'Berasal dari aksara Pallawa India Selatan abad ke-7. Salah satu sistem tulisan tertua di Asia Tenggara.',khm:'អក្សរខ្មែរ — Aksara Khmer'},
  {ico:'🌾',title:'Pertanian Padi',desc:'Tonle Sap, danau air tawar terbesar Asia Tenggara, menjadi sumber kesuburan tanah Kamboja.',khm:'ស្រែ — Sawah Padi'},
  {ico:'⛩️',title:'Kehidupan Biksu',desc:'Hampir setiap desa memiliki kuil. Pria Khmer tradisional ditahbiskan sebagai biksu minimal sekali seumur hidup.',khm:'វត្ត — Kuil Budha'},
  {ico:'🔮',title:'Kepercayaan & Neak Ta',desc:'Selain Budha, masyarakat Khmer percaya Neak Ta (roh penjaga tanah) dan Arak (roh leluhur).',khm:'ព្រលឹង — Roh & Kepercayaan'},
];

// ============================================================
// KARAOKE SONGS — lagu dengan timestamp untuk sinkronisasi
// ============================================================
const KARAOKE_SONGS = [
  {
    title: 'ស្រីគ្រឹស្ថ — Srey Kres',
    artist: 'Ros Sereysothea',
    ytId: '',
    lines: [
      {time:0, k:'ស្រីគ្រឹស្ថ ស្អាតពណ៌ស', r:'Srey kres, s\'at poa sor', i:'Gadis kristal cantik berkulit putih'},
      {time:4, k:'ភ្នែកស្រស់ ដូចផ្ការ', r:'Phnek sros, douch phkar', i:'Mata indah bagai bunga'},
      {time:8, k:'ចិត្តខ្ញុំ ស្រឡាញ់នាង', r:'Chet khnhom, s\'ranh neang', i:'Hatiku mencintainya'},
      {time:12, k:'ស្នើសុំ ចងស្រស់', r:'S\'noe-som, chong sros', i:'Memohon untuk bersatu'},
      {time:16, k:'ខ្ញុំស្រឡាញ់អ្នក', r:'Khnhom s\'ranh neak', i:'Aku mencintaimu'},
      {time:20, k:'ជារចិត្តពិត', r:'Chea ro chet pit', i:'Dengan hati yang tulus'},
      {time:24, k:'ពុំចង់ឃ្លាតចាក', r:'Pom chong khloat chak', i:'Tidak mau berpisah'},
      {time:28, k:'គ្នារហូតដល់ស្លាប់', r:'Knia rohout dal slap', i:'Bersama hingga akhir hayat'},
    ]
  },
  {
    title: 'ដំណើរស្នេហ៍ — Damnear Sne',
    artist: 'Pop Modern',
    ytId: '',
    lines: [
      {time:0, k:'ដំណើរស្នេហ៍ ដែលយើងហើរ', r:'Damnear sne, del yeung haer', i:'Perjalanan cinta yang kita lalui'},
      {time:4, k:'ពីព្រឹក ដល់យប់', r:'Pi proek, dal yub', i:'Dari pagi hingga malam'},
      {time:8, k:'ជាមួយ គ្នា ជានិច្ច', r:'Chea muoy, knia chea noch', i:'Bersama selamanya'},
      {time:12, k:'ស្នេហ៍ ពិត ពុំ ស្លាប់', r:'Sne pit, pom slap', i:'Cinta sejati tidak mati'},
      {time:16, k:'ចាប់ ដៃ ដើរ ជាមួយ', r:'Chab dai, daer chea muoy', i:'Bergandengan tangan bersama'},
      {time:20, k:'ទៅ ចុង ផ្លូវ ស្នេហ៍', r:'Tov chong, phlov sne', i:'Menuju ujung jalan cinta'},
      {time:24, k:'ស្នេហ៍ ស្ងប់ ស្ងាត់', r:'Sne s\'ngob s\'ngat', i:'Cinta yang tenang dan damai'},
      {time:28, k:'ជា ជីវិត', r:'Chea chi-vit', i:'Adalah kehidupan'},
    ]
  },
];
